# Generated by Django 5.1.5 on 2025-03-30 07:48

import portal.utils.functions
import portal.utils.photoutils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mongeoid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('b', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('dh', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'mongeoid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Нэр')),
                ('verbose', models.CharField(max_length=160, verbose_name='Монгол')),
                ('path', models.CharField(max_length=160, verbose_name='Зам')),
            ],
            options={
                'verbose_name_plural': 'Action',
            },
        ),
        migrations.CreateModel(
            name='AdminUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('unit1', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit2', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit3', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'AdminUnit',
                'verbose_name_plural': 'Нэгжийн хил',
            },
        ),
        migrations.CreateModel(
            name='CenterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Цэгийн хэлбэр')),
                ('img', models.ImageField(upload_to=portal.utils.functions.photo_upload_path, verbose_name='Төв цэгийн хэлбэр')),
            ],
            options={
                'verbose_name_plural': 'Цэгийн хэлбэр',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CORS-ийн статус',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyIonex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'doy'],
            },
        ),
        migrations.CreateModel(
            name='DailyNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'doy'],
            },
        ),
        migrations.CreateModel(
            name='DailyOrbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doy', models.IntegerField(blank=True, null=True)),
                ('gpsweek', models.IntegerField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'doy'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(null=True, unique=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Багаж эзэмшигч',
            },
        ),
        migrations.CreateModel(
            name='FirstLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('code', models.CharField(default='B', max_length=1)),
            ],
            options={
                'verbose_name_plural': '1-р ангилал',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GeodeticCoordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Геодезийн солбицлын төрөл /UTM, Cartesian/',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeodeticNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Геодезийн сүлжээ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Газар зүйн нэр')),
                ('source', models.CharField(blank=True, choices=[('Уламжлалт', 'Уламжлалт нэр'), ('Үүсмэл', 'Үүсмэл нэр')], default='Уламжлалт', max_length=100, null=True, verbose_name='Гарал үүсэл')),
            ],
            options={
                'verbose_name_plural': 'Газар зүйн нэр',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IgsAntenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('photo_element', models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Фаз параметр')),
            ],
            options={
                'verbose_name_plural': 'IGS антена',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IgsReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'IGS хүлээн авагч',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Itrf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ITRF version',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True)),
                ('order', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Менью',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('is_user', models.BooleanField(default=False)),
                ('is_board', models.BooleanField(default=False)),
                ('is_org', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Менью групп',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='MAGPC', max_length=160, verbose_name='Sms')),
                ('response', models.CharField(default='Status', max_length=160, verbose_name='Status')),
                ('sendto', models.CharField(max_length=160, verbose_name='Дугаар')),
                ('negj', models.CharField(max_length=160, verbose_name='Үлдэгдэл')),
            ],
            options={
                'verbose_name_plural': 'Sms',
            },
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Тайлбар')),
                ('is_related_point', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Зургийн төрөл',
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Албан тушаал')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Удирдах?')),
                ('is_laboratory', models.BooleanField(default=False, verbose_name='Лаборатори?')),
                ('rank', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Албан тушаал',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Төрөл')),
            ],
            options={
                'verbose_name_plural': 'Хөрсний төрөл',
            },
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sso_user_id', models.CharField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=portal.utils.photoutils.get_profile_photo_upload_path, verbose_name='Лого')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_citizen', models.BooleanField(default=False, verbose_name='')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Утас')),
                ('register', models.CharField(error_messages={'unique': 'Регистр бүртгэгдсэн байна'}, max_length=30, unique=True, verbose_name='Регистр')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Хэрэглэгч',
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=200, null=True, verbose_name='app')),
                ('name', models.CharField(max_length=200, verbose_name='Бүтэц')),
                ('bgcolor', models.CharField(max_length=200, verbose_name='Өнгө')),
                ('eng', models.CharField(max_length=200, verbose_name='English')),
                ('order', models.IntegerField(default=1)),
                ('content', models.CharField(verbose_name='Танилцуулга')),
                ('is_outside', models.BooleanField(default=False, verbose_name='Бие даасан')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardorgs', to=settings.AUTH_USER_MODEL, verbose_name='Байгууллага')),
            ],
            options={
                'verbose_name_plural': 'Системийн оролцогч',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BoardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('name', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('content', models.CharField(default='Санал хүсэлт:', verbose_name='Агуулга')),
                ('requesttype', models.PositiveIntegerField(blank=True, choices=[(1, 'Хүсэлт'), (2, 'Гомдол'), (3, 'Талархал')], db_index=True, null=True, verbose_name='Төрөл')),
                ('attach', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Хавсралт')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд уншсан')),
                ('views', models.IntegerField(default=1, verbose_name='Уншсан')),
                ('is_open', models.BooleanField(default=False, verbose_name='Нээлттэй')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.board', verbose_name='Хариуцах нэгж')),
                ('readers', models.ManyToManyField(blank=True, related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Уншсан хэрэглэгчид')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'Хүсэлт',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('decision', models.PositiveIntegerField(choices=[(5, 'Арга хэмжээ'), (1, 'Тушаал'), (2, 'Хурлын тэмдэглэл'), (3, 'Албан бичиг'), (4, 'Бүх гишүүдийн хурлын тэмдэглэл')], db_index=True, null=True, verbose_name='Шийдвэрийн төрөл')),
                ('name', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('content', models.CharField(verbose_name='Агуулга')),
                ('is_open', models.BooleanField(default=False, verbose_name='Нээлттэй эсэх')),
                ('attach', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Шийдвэрийн хавсралт')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boarddocuments', to='core.board', verbose_name='Хариуцах нэгж')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.boardrequest', verbose_name='Хүсэлт')),
            ],
            options={
                'verbose_name_plural': 'Нэгжийн шийдвэр',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Cors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=4, verbose_name='Станцын нэр')),
                ('org_user_id', models.UUIDField(blank=True, null=True, verbose_name='Хариуцах байгууллага')),
                ('contact1_user_id', models.UUIDField(blank=True, null=True, verbose_name='Хариуцах ажилтан')),
                ('contact2_user_id', models.UUIDField(blank=True, null=True, verbose_name='Шаардлагатай үед')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.corsstatus')),
            ],
            options={
                'verbose_name_plural': 'CORS',
                'ordering': ['site'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Эрх бүхий')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='Итгэмжлэл')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Лабораторийн эрх')),
                ('in_date', models.DateTimeField(blank=True, null=True, verbose_name='Орсон')),
                ('out_date', models.DateTimeField(blank=True, null=True, verbose_name='Гарсан')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to=models.Q(('type__name', 'Иргэн'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeorgs', to=settings.AUTH_USER_MODEL, verbose_name='Байгууллага')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pos', verbose_name='Албан тушаал')),
            ],
            options={
                'verbose_name_plural': 'Ажилтан',
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLabourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлөгдсөн')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Цалин')),
                ('shim', models.IntegerField(blank=True, null=True, verbose_name='Шимтгэл')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Жил')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Сар')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.employee', verbose_name='ажилтан')),
            ],
            options={
                'verbose_name_plural': 'НД төлөлт',
                'ordering': ['-employee'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('gnss_option', models.CharField(blank=True, max_length=200, null=True, verbose_name='Хиймэл дагуул')),
                ('directory', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ажлын фолдер')),
                ('report', models.FileField(blank=True, null=True, upload_to='', verbose_name='Тайлан')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Жил')),
                ('doy', models.IntegerField(blank=True, null=True, verbose_name='Өдөр')),
                ('url', models.URLField(blank=True)),
                ('qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('inquire', models.FileField(blank=True, upload_to=portal.utils.functions.file_upload_path)),
                ('itrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.itrf', verbose_name='Солбицлын тогтолцоо')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.corsstatus', verbose_name='Сүлжээний төрөл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'Бодолт',
                'ordering': ['-year', '-doy'],
            },
        ),
        migrations.CreateModel(
            name='MassMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('name', models.CharField(max_length=2000, verbose_name='Гарчиг')),
                ('content', models.CharField(default='Агуулга: ', max_length=5000, verbose_name='Агуулга')),
                ('counter', models.PositiveIntegerField(choices=[(1, 'Системд бүртгэлтэй бүх хэрэглэгчдэд'), (2, 'Багаж бүртгэлтэй хэрэглэгч'), (3, 'Зорилтод бүлэг')], db_index=True, null=True, verbose_name='Бүлэг')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'Масс имэйл',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_board', models.BooleanField(default=False)),
                ('is_org', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('can_read', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_accept', models.BooleanField(default=False)),
                ('can_decline', models.BooleanField(default=False)),
                ('board_can_read', models.BooleanField(default=False)),
                ('board_can_create', models.BooleanField(default=False)),
                ('board_can_update', models.BooleanField(default=False)),
                ('board_can_delete', models.BooleanField(default=False)),
                ('board_can_accept', models.BooleanField(default=False)),
                ('board_can_decline', models.BooleanField(default=False)),
                ('board_can_copy', models.BooleanField(default=False)),
                ('org_can_read', models.BooleanField(default=False)),
                ('org_can_create', models.BooleanField(default=False)),
                ('org_can_update', models.BooleanField(default=False)),
                ('org_can_delete', models.BooleanField(default=False)),
                ('org_can_accept', models.BooleanField(default=False)),
                ('org_can_decline', models.BooleanField(default=False)),
                ('read_url', models.CharField(blank=True, max_length=255)),
                ('create_url', models.CharField(blank=True, max_length=255)),
                ('update_url', models.CharField(blank=True, max_length=255)),
                ('delete_url', models.CharField(blank=True, max_length=255)),
                ('accept_url', models.CharField(blank=True, max_length=255)),
                ('decline_url', models.CharField(blank=True, max_length=255)),
                ('board_read_url', models.CharField(blank=True, max_length=255)),
                ('board_create_url', models.CharField(blank=True, max_length=255)),
                ('board_update_url', models.CharField(blank=True, max_length=255)),
                ('board_delete_url', models.CharField(blank=True, max_length=255)),
                ('board_accept_url', models.CharField(blank=True, max_length=255)),
                ('board_decline_url', models.CharField(blank=True, max_length=255)),
                ('board_copy_url', models.CharField(blank=True, max_length=255)),
                ('board', models.ManyToManyField(blank=True, related_name='permittedboards', to='core.board')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permittedcontents', to='contenttypes.contenttype')),
                ('menu_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardgroups', to='core.menugroup')),
                ('menu_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orggroups', to='core.menugroup')),
                ('menu_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroups', to='core.menugroup')),
                ('org', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permittedorgs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permittedusers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Эрхийн тохиргоо',
                'ordering': ['-model_name'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Файл')),
                ('marker_num', models.CharField(max_length=1000)),
                ('surveyor', models.UUIDField(blank=True, null=True)),
                ('is_static', models.BooleanField(blank=True, default=True, null=True, verbose_name='Статик?')),
                ('geodeticnetwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geodeticnetworks', to='core.geodeticnetworktype', verbose_name='Геодезийн сүлжээ')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobpoints', to='core.job', verbose_name='Бодолт')),
            ],
            options={
                'verbose_name_plural': 'Цэг, тэмдэгт',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=1000, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomek', models.CharField(blank=True, max_length=8, null=True, verbose_name='M100k Нэрлэвэр')),
                ('unit1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аймаг')),
                ('unit2', models.CharField(blank=True, max_length=21, null=True, verbose_name='Сумын нэр')),
                ('unit3', models.CharField(blank=True, max_length=21, null=True, verbose_name='Багийн нэр')),
                ('geoloc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('descritpion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Байршлын тэмдэглэл')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='Шинээр суулгасан')),
                ('final_x', models.FloatField(blank=True, null=True, verbose_name='Бодсон X')),
                ('final_y', models.FloatField(blank=True, null=True, verbose_name='Бодсон Y')),
                ('final_z', models.FloatField(blank=True, null=True, verbose_name='Бодсон Z')),
                ('x_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн X')),
                ('y_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн Y')),
                ('z_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн Z')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.centertype', verbose_name='Төвийн хэлбэр')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='BaganaGeonames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='Газарзүйн нэр')),
                ('geoname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geonames', to='core.geoname', verbose_name='Нэр')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointgeonames', to='core.point', verbose_name='Тэмдэг')),
            ],
            options={
                'verbose_name_plural': 'Газарзүйн нэр',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaganaDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance1', models.FloatField(blank=True, null=True, verbose_name='Зай 1')),
                ('distance2', models.FloatField(blank=True, null=True, verbose_name='Зай 2')),
                ('azimuth1', models.FloatField(blank=True, null=True, verbose_name='Азимут 1')),
                ('azimuth2', models.FloatField(blank=True, null=True, verbose_name='Азимут 2')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='Тайлбар')),
                ('bagana1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstdirections', to='core.point', verbose_name='Багана 1')),
                ('bagana2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconddirections', to='core.point', verbose_name='Багана 2')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointdirections', to='core.point', verbose_name='Тэмдэг')),
            ],
            options={
                'verbose_name_plural': 'Тэмдгийн чиглэл',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaganaDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='Тайлбар')),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='bg-blue-700 hover:bg-blue-800 text-white', max_length=100, verbose_name='Өнгө')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.point', verbose_name='Тэмдэг')),
            ],
            options={
                'verbose_name_plural': 'Тэмдгийн нотолгоо',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaganaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='Тайлбар')),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='bg-blue-700 hover:bg-blue-800 text-white', max_length=100, verbose_name='Өнгө')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='core.point', verbose_name='Тэмдэг')),
            ],
            options={
                'verbose_name_plural': 'Тэмдгийн төв',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=portal.utils.functions.photo_upload_path)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.point', verbose_name='Цэг')),
                ('type', models.ForeignKey(limit_choices_to={'is_related_point': True}, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.phototype', verbose_name='Төрөл')),
            ],
            options={
                'verbose_name_plural': 'Цэгийн зураг',
                'ordering': ['point__name'],
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.board', verbose_name='Нэгж')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to=settings.AUTH_USER_MODEL, verbose_name='Гишүүн')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.boarddocument', verbose_name='Шийдвэр')),
                ('pos', models.ForeignKey(blank=True, default='Undefined', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pos', verbose_name='Үүрэг')),
            ],
            options={
                'verbose_name_plural': 'Бүтцийн гишүүн',
                'ordering': ['-solution__created_date'],
            },
        ),
        migrations.CreateModel(
            name='Qpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(default=1, verbose_name='Дүн')),
                ('desc', models.CharField(max_length=200, verbose_name='Гүйлгээний утга')),
                ('receiver', models.CharField(blank=True, null=True, verbose_name='Хүлээн авагчийн регистр')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлсөн')),
                ('invoice_id', models.CharField(blank=True, max_length=40, verbose_name='QPAY дугаар')),
                ('qp_qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('call_back', models.URLField(blank=True)),
                ('payment_id', models.CharField(blank=True, max_length=40, verbose_name='QPAY төлбөрийн дугаар')),
                ('wallet', models.CharField(blank=True, max_length=40, verbose_name='Төрөл')),
                ('ebarimt_id', models.CharField(blank=True, max_length=40, verbose_name='Ebarim дугаар')),
                ('ebarimt_bill_id', models.CharField(blank=True, max_length=200, verbose_name='ДДТД')),
                ('ebarimt_qr_data', models.CharField(blank=True, max_length=5000, verbose_name='Ebarimt data')),
                ('ebarimt_qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('ebarimt_lottery_id', models.CharField(blank=True, max_length=5000, verbose_name='Ebarimt сугалааны дугаар')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_%(class)ss', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'Гүйлгээ',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='QPAY дугаар')),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Дүн')),
                ('logo', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('link', models.CharField(blank=True, max_length=3000)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='core.qpay', verbose_name='Банк')),
            ],
            options={
                'verbose_name_plural': 'Банк',
            },
        ),
        migrations.CreateModel(
            name='QpayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, null=True, verbose_name='type')),
                ('expire', models.CharField(blank=True, null=True, verbose_name='expire')),
                ('refresh_expire', models.CharField(blank=True, null=True, verbose_name='refresh expire')),
                ('refresh', models.CharField(blank=True, null=True, verbose_name='refresh')),
                ('access', models.CharField(blank=True, null=True, verbose_name='access')),
                ('scope', models.CharField(blank=True, null=True, verbose_name='scope')),
                ('session_state', models.CharField(blank=True, null=True, verbose_name='session_state')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.qpay', verbose_name='Төлбөр')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc', models.FloatField(blank=True, null=True, verbose_name='Чанар')),
                ('qc_m1', models.FloatField(blank=True, null=True, verbose_name='Mp1')),
                ('qc_m2', models.FloatField(blank=True, null=True, verbose_name='Mp2')),
                ('qc_slip', models.FloatField(blank=True, null=True, verbose_name='slips')),
                ('qc_sn1', models.FloatField(blank=True, null=True, verbose_name='Sn1')),
                ('qc_sn2', models.FloatField(blank=True, null=True, verbose_name='Sn2')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('head_x', models.FloatField(blank=True, null=True, verbose_name='apr X')),
                ('head_y', models.FloatField(blank=True, null=True, verbose_name='apr Y')),
                ('head_z', models.FloatField(blank=True, null=True, verbose_name='apr Z')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='RinexReady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rinex', models.CharField(blank=True, max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doy', models.IntegerField(blank=True, null=True)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('cors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cors')),
            ],
            options={
                'ordering': ['year', 'doy'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=160, verbose_name='Нэр')),
                ('actions', models.ManyToManyField(blank=True, null=True, related_name='permissions', to='core.action')),
            ],
            options={
                'verbose_name_plural': 'Эрхийн тохиргоо',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SecondLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondname', models.CharField(max_length=50)),
                ('code', models.CharField(default='01', max_length=2)),
                ('firstname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firstlevel')),
            ],
            options={
                'verbose_name_plural': '2-р ангилал',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(blank=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentsubmenus', to='contenttypes.contenttype')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.menu')),
            ],
            options={
                'verbose_name_plural': 'Дэд менью',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='action',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.submenu'),
        ),
        migrations.CreateModel(
            name='ThirdLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirdname', models.CharField(max_length=200)),
                ('code', models.CharField(default='01', max_length=2)),
                ('geomtype', models.CharField(choices=[('Point', 'Цэг'), ('Line', 'Шугам'), ('Polygon', 'Талбай')], default='Point', max_length=50, verbose_name='Геометр төрөл')),
                ('desciption', models.CharField(default='Уул, хавцал зэрэг газарт хэсэг хэсгээр овооролдон орших сул хад чулуу', max_length=1000)),
                ('secondname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secondlevel')),
            ],
            options={
                'verbose_name_plural': '3-р ангилал',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='geoname',
            name='thirdlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thirdlevel', verbose_name='Газар зүйн нэрийн төрөл'),
        ),
        migrations.CreateModel(
            name='UserGnss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ant_serial', models.CharField(blank=True, max_length=40, null=True, verbose_name='Антены дугаар')),
                ('photo_phase', models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Antenna Phase')),
                ('antenna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userantennas', to='core.igsantenna', verbose_name='Antenna (IGS)')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdevice', to='core.device', verbose_name='Багаж')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreceivers', to='core.igsreceiver', verbose_name='Receiver(IGS)')),
            ],
            options={
                'verbose_name_plural': 'Хэрэглэгчийн багаж',
                'ordering': ['receiver'],
            },
        ),
        migrations.CreateModel(
            name='VeloMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('b', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('ve', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('vn', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('vx', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('vy', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('vz', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itrf')),
            ],
            options={
                'verbose_name_plural': 'Хурдны векторын интерполяци',
                'ordering': ['b'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=40, null=True, verbose_name='эхл (C)')),
                ('end_temperature', models.CharField(blank=True, max_length=40, null=True, verbose_name='төгс (C)')),
                ('pressure', models.CharField(blank=True, max_length=40, null=True, verbose_name='эхл (мм.муб)')),
                ('end_pressure', models.CharField(blank=True, max_length=40, null=True, verbose_name='төгс (мм.муб)')),
                ('humadity', models.CharField(blank=True, max_length=40, null=True, verbose_name='эхл (%)')),
                ('end_humadity', models.CharField(blank=True, max_length=40, null=True, verbose_name='төгс (%)')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Хөрсний шинж')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.point')),
                ('soiltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.soiltype', verbose_name='Хөрсний төрөл')),
            ],
        ),
    ]
