# Generated by Django 5.1.5 on 2025-03-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeelabourrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='menu_org',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='menu_board',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='menu_user',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='board',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='content',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='org',
        ),
        migrations.RemoveField(
            model_name='modelpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='Эрх'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(related_name='permissions', to='core.action'),
        ),
        migrations.DeleteModel(
            name='BoardDocument',
        ),
        migrations.DeleteModel(
            name='BoardMember',
        ),
        migrations.DeleteModel(
            name='Pos',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeLabourRecord',
        ),
        migrations.DeleteModel(
            name='MenuGroup',
        ),
        migrations.DeleteModel(
            name='ModelPermission',
        ),
    ]
