# Generated by Django 5.1.5 on 2025-03-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_boardmember_solution_remove_boardmember_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.role', verbose_name='Эрх'),
        ),
    ]
