# Generated by Django 5.1.5 on 2025-03-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_remoteuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='Эрх'),
        ),
    ]
