# Generated by Django 5.1.5 on 2025-04-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_remoteuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='verbose',
            new_name='key',
        ),
    ]
