# Generated by Django 5.1.5 on 2025-04-19 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_rename_verbose_action_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('key', models.CharField(blank=True, max_length=1000, null=True)),
                ('app', models.CharField(blank=True, max_length=1000, null=True)),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Тогтмол',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': 'Үйлдэл'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Меню'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='path',
        ),
        migrations.AddField(
            model_name='action',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='actions',
            field=models.ManyToManyField(related_name='submenuactions', to='core.action'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='path',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Монгол'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontents', to='contenttypes.contenttype'),
        ),
    ]
