# Generated by Django 5.1.5 on 2025-04-19 10:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_constant_alter_action_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='Байгууллага')),
            ],
        ),
        migrations.CreateModel(
            name='Contributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Оролцсон хүний нэр')),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M1000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M10000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M100000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M2000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M25000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M5000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.CreateModel(
            name='M50000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
            ],
        ),
        migrations.RemoveField(
            model_name='baganacenter',
            name='point',
        ),
        migrations.RemoveField(
            model_name='baganadesc',
            name='point',
        ),
        migrations.RemoveField(
            model_name='baganadirection',
            name='bagana1',
        ),
        migrations.RemoveField(
            model_name='baganadirection',
            name='bagana2',
        ),
        migrations.RemoveField(
            model_name='baganadirection',
            name='point',
        ),
        migrations.RemoveField(
            model_name='baganageonames',
            name='geoname',
        ),
        migrations.RemoveField(
            model_name='baganageonames',
            name='point',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='boardrequest',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardrequest',
            name='readers',
        ),
        migrations.RemoveField(
            model_name='boardrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='center',
        ),
        migrations.RemoveField(
            model_name='cors',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rinexready',
            name='cors',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.DeleteModel(
            name='DailyIonex',
        ),
        migrations.DeleteModel(
            name='DailyNav',
        ),
        migrations.DeleteModel(
            name='DailyOrbit',
        ),
        migrations.RemoveField(
            model_name='usergnss',
            name='device',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='device',
        ),
        migrations.DeleteModel(
            name='GeodeticCoordType',
        ),
        migrations.RemoveField(
            model_name='point',
            name='geodeticnetwork',
        ),
        migrations.RemoveField(
            model_name='usergnss',
            name='antenna',
        ),
        migrations.RemoveField(
            model_name='usergnss',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='job',
            name='itrf',
        ),
        migrations.RemoveField(
            model_name='velomap',
            name='network',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='point',
            name='job',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='point',
        ),
        migrations.RemoveField(
            model_name='paymentbank',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='pointphoto',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pointphoto',
            name='point',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='point',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='point',
        ),
        migrations.RemoveField(
            model_name='qpay',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='qpay',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qpaytoken',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soiltype',
        ),
        migrations.DeleteModel(
            name='Mongeoid',
        ),
        migrations.AlterModelOptions(
            name='firstlevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='geoname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secondlevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thirdlevel',
            options={},
        ),
        migrations.RenameField(
            model_name='geoname',
            old_name='thirdlevel',
            new_name='typename',
        ),
        migrations.AddField(
            model_name='geoname',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Хувийн хэрэг хөтөлсөн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoname',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoname',
            name='desc_loc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ерөнхий байрлал, тайлбар'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='document',
            field=models.ManyToManyField(blank=True, limit_choices_to={'key': 'GEONAME_DOCUMENTS'}, null=True, related_name='geonamedocuments', to='core.constant', verbose_name='Нотлох баримтууд'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geoname',
            name='is_changed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='geoname',
            name='is_in_protocol',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocolchoice', to='core.constant', verbose_name='Протоколын жагсаалтад'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='is_in_san',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanchoice', to='core.constant', verbose_name='Нэрийн санд'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='is_in_uix',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uihchoice', to='core.constant', verbose_name='УИХТогтоолд'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='m100k',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m100kchoice', to='core.constant', verbose_name='1:100 000-ны зурагт'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='m10k',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m10kchoice', to='core.constant', verbose_name='1:10 000-ны зурагт'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='m25k',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m25kchoice', to='core.constant', verbose_name='1:25 000-ны зурагт'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='m50k',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m50kchoice', to='core.constant', verbose_name='1:50 000-ны зурагт'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='name_index',
            field=models.CharField(default='G-4', max_length=50, verbose_name='Нэрийн зургийн индекс'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='nameeng',
            field=models.CharField(max_length=50, null=True, verbose_name='Галиг'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='geoname/photo', verbose_name='Орчны зураг'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='schema',
            field=models.ImageField(blank=True, null=True, upload_to='geoname/photo', verbose_name='Байршлын схем'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='uniqid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoname',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='source',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_SOURCES'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='Гарал үүсэл'),
        ),
        migrations.AlterField(
            model_name='thirdlevel',
            name='geomtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_GEOMTYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='Геометр төрөл'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actor', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='contributer',
            name='geoname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.geoname', verbose_name='Газар зүйн нэр'),
        ),
        migrations.AddField(
            model_name='contributer',
            name='response',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to='core.constant', verbose_name='Үүрэг/Албан тушаал'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='geoname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.geoname', verbose_name='Байрлал'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.adminunits', verbose_name='Нэгж'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m1k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M1k', to='core.m1000', verbose_name='M1k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m10k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M10k', to='core.m10000', verbose_name='M10k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m100k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M100k', to='core.m100000', verbose_name='M100k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m2k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2k', to='core.m2000', verbose_name='M2k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m25k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M25k', to='core.m25000', verbose_name='M25k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m5k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M5k', to='core.m5000', verbose_name='M5k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m50k',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M50k', to='core.m50000', verbose_name='M50k'),
        ),
        migrations.DeleteModel(
            name='BaganaCenter',
        ),
        migrations.DeleteModel(
            name='BaganaDesc',
        ),
        migrations.DeleteModel(
            name='BaganaDirection',
        ),
        migrations.DeleteModel(
            name='BaganaGeonames',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardRequest',
        ),
        migrations.DeleteModel(
            name='CenterType',
        ),
        migrations.DeleteModel(
            name='Cors',
        ),
        migrations.DeleteModel(
            name='RinexReady',
        ),
        migrations.DeleteModel(
            name='CorsStatus',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='GeodeticNetworkType',
        ),
        migrations.DeleteModel(
            name='IgsAntenna',
        ),
        migrations.DeleteModel(
            name='IgsReceiver',
        ),
        migrations.DeleteModel(
            name='UserGnss',
        ),
        migrations.DeleteModel(
            name='Itrf',
        ),
        migrations.DeleteModel(
            name='VeloMap',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='PaymentBank',
        ),
        migrations.DeleteModel(
            name='PhotoType',
        ),
        migrations.DeleteModel(
            name='PointPhoto',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='Qpay',
        ),
        migrations.DeleteModel(
            name='QpayToken',
        ),
        migrations.DeleteModel(
            name='SoilType',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
