# Generated by Django 5.1.5 on 2025-07-08 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_actor_contributer_locationinfo_m1000_m10000_m100000_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constant',
            old_name='app',
            new_name='code',
        ),
        migrations.AddField(
            model_name='constant',
            name='color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='constant',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='constant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.constant', verbose_name='Дэд тогтмол'),
        ),
    ]
