# Generated by Django 5.1.5 on 2025-07-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_app_constant_code_constant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='content',
        ),
        migrations.AddField(
            model_name='role',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.submenu'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='men',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MENUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.constant'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
