# Generated by Django 5.1.5 on 2025-07-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_role_actions_remove_submenu_actions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='men',
            new_name='menu',
        ),
        migrations.AddField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(limit_choices_to={'key': 'ACTIONS'}, related_name='permissions', to='core.constant'),
        ),
    ]
