# Generated by Django 5.1.5 on 2025-07-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_men_submenu_menu_role_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='submenu',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(blank=True, limit_choices_to={'key': 'ACTIONS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.constant')),
                ('submenu', models.ForeignKey(blank=True, limit_choices_to={'key': 'SUBMENUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenuactions', to='core.constant')),
            ],
            options={
                'verbose_name_plural': 'Үйлдэл',
            },
        ),
        migrations.AlterField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(related_name='permissions', to='core.action'),
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
