# Generated by Django 5.1.5 on 2025-07-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_role_submenu_action_alter_role_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.ForeignKey(blank=True, limit_choices_to={'key__in': ['create', 'delete', 'update', 'list']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.constant'),
        ),
    ]
