# Generated by Django 5.1.5 on 2025-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_action_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.ManyToManyField(limit_choices_to={'key__in': ['create', 'delete', 'update', 'list']}, to='core.constant'),
        ),
    ]
