# Generated by Django 5.1.5 on 2025-07-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_action_action_action_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='actions',
        ),
    ]
