# Generated by Django 5.1.5 on 2025-07-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_action_action_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='actions',
            field=models.ForeignKey(blank=True, limit_choices_to={'key__in': ['create', 'delete', 'update', 'list']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant'),
        ),
    ]
