# Generated by Django 5.1.5 on 2025-07-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_action_actions_action_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='actions',
            new_name='action',
        ),
    ]
