# Generated by Django 5.1.5 on 2025-07-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_actions_action_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(related_name='permissions', to='core.constant'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
