# Generated by Django 5.1.5 on 2025-07-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_role_actions_delete_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.firstlevel', verbose_name='Дээд'),
        ),
    ]
