# Generated by Django 5.1.5 on 2025-07-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_firstlevel_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstLevel',
            new_name='Level',
        ),
    ]
