# Generated by Django 5.1.5 on 2025-07-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_firstlevel_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='firstname',
            new_name='name',
        ),
    ]
