# Generated by Django 5.1.5 on 2025-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(default='B', max_length=3),
        ),
    ]
