# Generated by Django 5.1.5 on 2025-07-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='desciption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='geomtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_GEOMTYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='Геометр төрөл'),
        ),
    ]
