# Generated by Django 5.1.5 on 2025-07-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_level_desciption_level_geomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='desciption',
            new_name='description',
        ),
    ]
