# Generated by Django 5.1.5 on 2025-07-09 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_desciption_level_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdlevel',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='thirdlevel',
            name='geomtype',
        ),
        migrations.AlterField(
            model_name='geoname',
            name='typename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level', verbose_name='Газар зүйн нэрийн төрөл'),
        ),
        migrations.DeleteModel(
            name='SecondLevel',
        ),
        migrations.DeleteModel(
            name='ThirdLevel',
        ),
    ]
