# Generated by Django 5.1.5 on 2025-07-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_thirdlevel_secondname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoname',
            old_name='typename',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='document',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='is_in_protocol',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='is_in_san',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='is_in_uix',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='m100k',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='m10k',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='m25k',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='m50k',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='schema',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('signDate', models.DateField(blank=True, null=True, verbose_name='Батлагдсан огноо')),
                ('docType', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_DOCS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namedocuments', to='core.constant', verbose_name='Төрөл')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namedocs', to='core.geoname', verbose_name='Газар зүйн нэр')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
