# Generated by Django 5.1.5 on 2025-07-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_typename_geoname_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoname',
            old_name='desc_loc',
            new_name='description',
        ),
    ]
