# Generated by Django 5.1.5 on 2025-07-09 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_desc_loc_geoname_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='created',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='updated',
        ),
        migrations.AddField(
            model_name='geoname',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Бүртгэсэн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoname',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Сүүлд үзсэн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoname',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Хандалт'),
        ),
    ]
