# Generated by Django 5.1.5 on 2025-07-09 07:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_geoname_created_remove_geoname_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='actor',
        ),
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('unit', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.adminunit', verbose_name='Дээд хил')),
            ],
            options={
                'verbose_name_plural': 'Хил',
            },
        ),
    ]
