# Generated by Django 5.1.5 on 2025-07-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_geoname_actor_adminunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.adminunit', verbose_name='Нэгж'),
        ),
    ]
