# Generated by Django 5.1.5 on 2025-07-09 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_geoname_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoname',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Хувийн хэрэг хөтөлсөн'),
        ),
    ]
