# Generated by Django 5.1.5 on 2025-07-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_geoname_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='unit',
        ),
        migrations.AddField(
            model_name='geoname',
            name='unit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aimagnames', to='core.adminunit', verbose_name='Нэгж'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='unit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sumnames', to='core.adminunit', verbose_name='Нэгж'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='unit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagnames', to='core.adminunit', verbose_name='Нэгж'),
        ),
    ]
