# Generated by Django 5.1.5 on 2025-07-10 04:44

import portal.utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_geoname_unit_geoname_unit1_geoname_unit2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('file', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Файл')),
                ('geomtype', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_GEOMTYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='Геометр төрөл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
