# Generated by Django 5.1.5 on 2025-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_geofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='m1000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m10000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m100000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m2000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m25000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m5000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m50000',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m100k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m10k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m1k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m25k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m2k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m50k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='m5k',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='unit',
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m100k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M100k', to='core.m100000', verbose_name='M100k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m10k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M10k', to='core.m10000', verbose_name='M10k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m1k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M1k', to='core.m1000', verbose_name='M1k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m25k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M25k', to='core.m25000', verbose_name='M25k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m2k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M2k', to='core.m2000', verbose_name='M2k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m50k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M50k', to='core.m50000', verbose_name='M50k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='m5k',
            field=models.ManyToManyField(blank=True, null=True, related_name='M5k', to='core.m5000', verbose_name='M5k'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='units', to='core.adminunits', verbose_name='Нэгж'),
        ),
    ]
