# Generated by Django 5.1.5 on 2025-07-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_m1000_is_mapped_m10000_is_mapped_m100000_is_mapped_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationInfo',
            new_name='Location',
        ),
    ]
