# Generated by Django 5.1.5 on 2025-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_locationinfo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='geoname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='location',
            name='m100k',
            field=models.ManyToManyField(related_name='M100k', to='core.m100000', verbose_name='M100k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m10k',
            field=models.ManyToManyField(related_name='M10k', to='core.m10000', verbose_name='M10k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m1k',
            field=models.ManyToManyField(related_name='M1k', to='core.m1000', verbose_name='M1k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m25k',
            field=models.ManyToManyField(related_name='M25k', to='core.m25000', verbose_name='M25k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m2k',
            field=models.ManyToManyField(related_name='M2k', to='core.m2000', verbose_name='M2k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m50k',
            field=models.ManyToManyField(related_name='M50k', to='core.m50000', verbose_name='M50k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='m5k',
            field=models.ManyToManyField(related_name='M5k', to='core.m5000', verbose_name='M5k'),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit',
            field=models.ManyToManyField(related_name='units', to='core.adminunits', verbose_name='Нэгж'),
        ),
    ]
