# Generated by Django 5.1.5 on 2025-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='unit',
            field=models.ManyToManyField(related_name='units', to='core.adminunit', verbose_name='Нэгж'),
        ),
    ]
