# Generated by Django 5.1.5 on 2025-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_location_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminunit',
            name='centerName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
