# Generated by Django 5.1.5 on 2025-07-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_adminunit_centername'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminunit',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.constant', verbose_name='UNIT_LEVEL'),
        ),
    ]
