# Generated by Django 5.1.5 on 2025-07-14 02:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_adminunit_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('unitname', models.CharField(blank=True, max_length=1000, null=True)),
                ('nationallevel', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Нэгжийн хил',
                'managed': False,
            },
        ),
    ]
