# Generated by Django 5.1.5 on 2025-07-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_center'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='center',
            table='center',
        ),
    ]
