# Generated by Django 5.1.5 on 2025-07-14 02:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_center_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminunit',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
