# Generated by Django 5.1.5 on 2025-07-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_adminunit_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUnits',
        ),
        migrations.DeleteModel(
            name='Center',
        ),
    ]
