# Generated by Django 5.1.5 on 2025-07-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_delete_adminunits_delete_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='unit1',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='unit2',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='unit3',
        ),
    ]
