# Generated by Django 5.1.5 on 2025-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_geoname_unit1_remove_geoname_unit2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='is_real',
            field=models.BooleanField(default=False, verbose_name='Байрлалтай эсэх'),
        ),
    ]
