# Generated by Django 5.1.5 on 2025-07-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_geoname_is_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoname',
            name='uniqid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
