# Generated by Django 5.1.5 on 2025-07-15 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_geoname_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_STATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoname_status', to='core.constant', verbose_name='Төлөв'),
        ),
    ]
