# Generated by Django 5.1.5 on 2025-07-15 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_geoname_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('signDate', models.DateField(blank=True, null=True, verbose_name='Батлагдсан огноо')),
                ('mapType', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_DOCS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappednames', to='core.constant', verbose_name='Төрөл')),
                ('name', models.ManyToManyField(related_name='mapnames', to='core.geoname', verbose_name='Газар зүйн нэр')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('signDate', models.DateField(blank=True, null=True, verbose_name='Батлагдсан огноо')),
                ('name', models.ManyToManyField(related_name='mappednames', to='core.geoname', verbose_name='Газар зүйн нэр')),
                ('remapType', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_DOCS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remapnames', to='core.constant', verbose_name='Төрөл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.ManyToManyField(related_name='docnames', to='core.geoname', verbose_name='Газар зүйн нэр'),
        ),
    ]
