# Generated by Django 5.1.5 on 2025-07-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_document_name_map_remap_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дугаар'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'DOCUMENT_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namedocuments', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='map',
            name='mapType',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MAP_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappednames', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='remap',
            name='remapType',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MAP_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remapnames', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
