# Generated by Django 5.1.5 on 2025-07-15 03:45

import portal.utils.functions
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_document_number_alter_document_doctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_geoname',
            field=models.BooleanField(default=False, verbose_name='Байрлалтай эсэх'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geom')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Зураг')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footmaps', to='core.map', verbose_name='FootPrint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ReMap',
        ),
    ]
