# Generated by Django 5.1.5 on 2025-07-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_map_is_geoname_alter_document_file_alter_map_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='name',
            new_name='names',
        ),
    ]
