# Generated by Django 5.1.5 on 2025-07-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_rename_name_document_names_rename_name_map_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='is_geoname',
            new_name='is_geofile',
        ),
    ]
