# Generated by Django 5.1.5 on 2025-07-15 07:26

import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_is_geoname_map_is_geofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footprint',
            name='thumb',
        ),
        migrations.AddField(
            model_name='map',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Зураг'),
        ),
    ]
