# Generated by Django 5.1.5 on 2025-07-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_footprint_thumb_map_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='decision',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'DECISION_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisionnames', to='core.constant', verbose_name='Шийдвэр'),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'SIGNER_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitnames', to='core.adminunit', verbose_name='Нэгж'),
        ),
    ]
