# Generated by Django 5.1.5 on 2025-07-16 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_geoname_status_document_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='org',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgusers', to=settings.AUTH_USER_MODEL, verbose_name='Байгууллага'),
        ),
    ]
