# Generated by Django 5.1.5 on 2025-07-18 01:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remoteuser_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geom')),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_mapped', models.BooleanField(default=False)),
                ('scale', models.ForeignKey(blank=True, limit_choices_to={'key': 'SCALES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
    ]
