# Generated by Django 5.1.5 on 2025-07-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_basemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='scale',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MAP_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
