# Generated by Django 5.1.5 on 2025-07-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_basemap_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m25000',
            name='is_mapped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
