# Generated by Django 5.1.5 on 2025-07-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_m25000_is_mapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m50000',
            name='is_mapped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
