# Generated by Django 5.1.5 on 2025-07-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_m50000_is_mapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='m100k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m10k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m1k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m25k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m2k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m50k',
        ),
        migrations.RemoveField(
            model_name='location',
            name='m5k',
        ),
        migrations.AddField(
            model_name='basemap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.basemap'),
        ),
        migrations.AddField(
            model_name='location',
            name='basemaps',
            field=models.ManyToManyField(related_name='coveredmaps', to='core.basemap', verbose_name='basemap'),
        ),
    ]
