# Generated by Django 5.1.5 on 2025-07-20 11:33

import portal.utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_location_m100k_remove_location_m10k_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barimt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Файл')),
                ('docType', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_DOCUMENTS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doccontributers', to='core.constant', verbose_name='Төрөл')),
                ('geoname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barimts', to='core.geoname')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Оролцсон хүний нэр')),
                ('geoname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='core.geoname')),
                ('response', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to='core.constant', verbose_name='Үүрэг/Албан тушаал')),
            ],
        ),
        migrations.CreateModel(
            name='ReMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champaign', models.CharField(blank=True, max_length=500, null=True, verbose_name='champaign')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дугаар')),
                ('barimts', models.ManyToManyField(related_name='remaps', to='core.barimt')),
                ('engineers', models.ManyToManyField(blank=True, limit_choices_to={'is_citizen': True}, null=True, related_name='engineers', to=settings.AUTH_USER_MODEL, verbose_name='Газар зүйн нэр')),
                ('org', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to=settings.AUTH_USER_MODEL, verbose_name='Байгууллага')),
                ('peoples', models.ManyToManyField(related_name='remaps', to='core.people')),
            ],
        ),
        migrations.DeleteModel(
            name='Contributer',
        ),
    ]
