# Generated by Django 5.1.5 on 2025-07-20 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_barimt_people_remap_delete_contributer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remap',
            name='peoples',
        ),
        migrations.RemoveField(
            model_name='barimt',
            name='geoname',
        ),
        migrations.RemoveField(
            model_name='remap',
            name='barimts',
        ),
        migrations.RemoveField(
            model_name='remap',
            name='number',
        ),
        migrations.RemoveField(
            model_name='remap',
            name='org',
        ),
        migrations.AddField(
            model_name='barimt',
            name='remap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectbarimts', to='core.remap', verbose_name='Баримт'),
        ),
        migrations.AddField(
            model_name='remap',
            name='geoname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remaps', to='core.geoname'),
        ),
        migrations.CreateModel(
            name='Champaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='champaign')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дугаар')),
                ('org', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to=settings.AUTH_USER_MODEL, verbose_name='Байгууллага')),
            ],
        ),
        migrations.AlterField(
            model_name='remap',
            name='champaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmaps', to='core.champaign'),
        ),
        migrations.CreateModel(
            name='Contrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Оролцсон хүний нэр')),
                ('remap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectcontribs', to='core.remap', verbose_name='Баримт')),
                ('response', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_VISIBLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to='core.constant', verbose_name='Үүрэг/Албан тушаал')),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
