# Generated by Django 5.1.5 on 2025-07-20 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_remap_peoples_remove_barimt_geoname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champaign',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, related_name='champaigns', to='core.adminunit', verbose_name='Байрлал'),
        ),
        migrations.AddField(
            model_name='champaign',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geom'),
        ),
    ]
