# Generated by Django 5.1.5 on 2025-07-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_champaign_area_champaign_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='champaign',
            name='signDate',
            field=models.DateField(blank=True, null=True, verbose_name='Батлагдсан огноо'),
        ),
    ]
