# Generated by Django 5.1.5 on 2025-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_champaign_signdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remap',
            name='champaign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Champaign',
        ),
    ]
