# Generated by Django 5.1.5 on 2025-08-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_remap_champaign_delete_champaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='Method')),
                ('description', models.TextField(null=True, verbose_name='Алдааны мэдэгдэл')),
                ('headers', models.TextField(null=True, verbose_name='Request headers')),
                ('scheme', models.TextField(null=True, verbose_name='Request scheme')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(null=True, verbose_name='Request data')),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='Method')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Алдааны дугаар')),
                ('description', models.TextField(null=True, verbose_name='Алдааны мэдэгдэл')),
                ('headers', models.TextField(null=True, verbose_name='Request headers')),
                ('scheme', models.TextField(null=True, verbose_name='Request scheme')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(null=True, verbose_name='Request data')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(verbose_name='Post data буюу body')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogPut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(verbose_name='Put data буюу body')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
    ]
