# Generated by Django 5.1.5 on 2025-08-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_error500_errors_requestlogdelete_requestlogget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlogget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestlogpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestlogput',
            name='user',
        ),
        migrations.AddField(
            model_name='error500',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='Query string'),
        ),
        migrations.AddField(
            model_name='error500',
            name='remote_ip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Remote IP'),
        ),
        migrations.AddField(
            model_name='error500',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID'),
        ),
        migrations.AddField(
            model_name='errors',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='Query string'),
        ),
        migrations.AddField(
            model_name='errors',
            name='remote_ip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Remote IP'),
        ),
        migrations.AddField(
            model_name='errors',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID'),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(blank=True, null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_index=True, max_length=10, verbose_name='Method')),
                ('status_code', models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='request status code')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Request body (JSON/raw)')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
            options={
                'verbose_name': 'Request log',
                'verbose_name_plural': 'Request logs',
            },
        ),
        migrations.DeleteModel(
            name='RequestLogDelete',
        ),
        migrations.DeleteModel(
            name='RequestLogGet',
        ),
        migrations.DeleteModel(
            name='RequestLogPost',
        ),
        migrations.DeleteModel(
            name='RequestLogPut',
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['url', 'datetime'], name='core_reques_url_a567d6_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['remote_ip', 'datetime'], name='core_reques_remote__53379c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['method', 'status_code'], name='core_reques_method_a92ffc_idx'),
        ),
    ]
