# Generated by Django 5.1.5 on 2025-08-31 02:46

import portal.utils.functions
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_requestlogget_user_remove_requestlogpost_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimt',
            name='docType',
        ),
        migrations.RemoveField(
            model_name='barimt',
            name='remap',
        ),
        migrations.RemoveField(
            model_name='contrib',
            name='remap',
        ),
        migrations.RemoveField(
            model_name='contrib',
            name='response',
        ),
        migrations.RemoveField(
            model_name='document',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='document',
            name='docType',
        ),
        migrations.RemoveField(
            model_name='document',
            name='names',
        ),
        migrations.RemoveField(
            model_name='document',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='map',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='geofile',
            name='geomtype',
        ),
        migrations.RemoveField(
            model_name='geofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='author',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='level',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='source',
        ),
        migrations.RemoveField(
            model_name='geoname',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='remap',
            name='geoname',
        ),
        migrations.RemoveField(
            model_name='map',
            name='names',
        ),
        migrations.RemoveField(
            model_name='level',
            name='geomtype',
        ),
        migrations.RemoveField(
            model_name='level',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='basemaps',
        ),
        migrations.RemoveField(
            model_name='location',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='map',
            name='mapType',
        ),
        migrations.RemoveField(
            model_name='map',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remap',
            name='engineers',
        ),
        migrations.CreateModel(
            name='Nomek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nomek', models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр')),
                ('is_mapped', models.BooleanField(default=False)),
                ('scale', models.ForeignKey(blank=True, limit_choices_to={'key': 'MAPSCALES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('number', models.CharField(blank=True, max_length=1000, null=True)),
                ('nomek', models.CharField(blank=True, max_length=8, null=True, verbose_name='M100k Нэрлэвэр')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerlocations', to='core.constant', verbose_name='Төвийн хэлбэр')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=portal.utils.functions.photo_upload_path)),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'key': 'POINT_PHOTO_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phototypes', to='core.constant', verbose_name='Зургийн төрөл')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.point', verbose_name='Цэг')),
            ],
            options={
                'verbose_name_plural': 'Цэгийн зураг',
                'ordering': ['point__name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.ForeignKey(blank=True, limit_choices_to={'key': 'DATUM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ellipsoids', to='core.constant', verbose_name='Datum')),
                ('epoch', models.ForeignKey(blank=True, limit_choices_to={'key': 'EPOCH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epochs', to='core.constant', verbose_name='Epoch')),
                ('system', models.ForeignKey(blank=True, limit_choices_to={'key': 'SYSTEM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.constant', verbose_name='System')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoloc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Байршлын тэмдэглэл')),
                ('final_x', models.FloatField(blank=True, null=True, verbose_name='Бодсон X')),
                ('final_y', models.FloatField(blank=True, null=True, verbose_name='Бодсон Y')),
                ('final_z', models.FloatField(blank=True, null=True, verbose_name='Бодсон Z')),
                ('x_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн X')),
                ('y_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн Y')),
                ('z_ref', models.FloatField(blank=True, null=True, verbose_name='Шилжсэн Z')),
                ('horht', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='Шинээр суулгасан')),
                ('agreementId', models.IntegerField(blank=True, null=True)),
                ('act', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('passport', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('journal', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineers', to=settings.AUTH_USER_MODEL, verbose_name='Хэмжсэн инженер')),
                ('network', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEODETICNETWORK'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkpoints', to='core.constant', verbose_name='Төрөл')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.point')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.system')),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Barimt',
        ),
        migrations.DeleteModel(
            name='Contrib',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='FootPrint',
        ),
        migrations.DeleteModel(
            name='GeoFile',
        ),
        migrations.DeleteModel(
            name='Geoname',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='ReMap',
        ),
    ]
