# Generated by Django 5.1.5 on 2025-08-31 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_barimt_doctype_remove_barimt_remap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomek',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.nomek'),
        ),
    ]
