# Generated by Django 5.1.5 on 2025-08-31 03:54

import portal.utils.functions
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_nomek_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='geoloc',
        ),
        migrations.AddField(
            model_name='measurement',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path),
        ),
        migrations.AddField(
            model_name='point',
            name='geoloc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='point',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='unitpoints', to='core.adminunit', verbose_name='Хил'),
        ),
        migrations.RemoveField(
            model_name='point',
            name='nomek',
        ),
        migrations.AddField(
            model_name='point',
            name='nomek',
            field=models.ManyToManyField(blank=True, null=True, related_name='nomekpoints', to='core.nomek', verbose_name='Нэрлэвэр'),
        ),
    ]
