# Generated by Django 5.1.5 on 2025-08-31 04:28

import portal.utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_measurement_geoloc_measurement_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['measurement__point__name'], 'verbose_name_plural': 'Цэгийн зураг'},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='act',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='report',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='point',
        ),
        migrations.AddField(
            model_name='measurement',
            name='deviceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.measurement', verbose_name='Цэг'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.point'),
        ),
        migrations.AlterField(
            model_name='point',
            name='nomek',
            field=models.ManyToManyField(related_name='nomekpoints', to='core.nomek', verbose_name='Нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='unit',
            field=models.ManyToManyField(related_name='unitpoints', to='core.adminunit', verbose_name='Хил'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actengineers', to=settings.AUTH_USER_MODEL, verbose_name='Хувийн хэрэг хөтөлсөн')),
                ('measurements', models.ManyToManyField(related_name='acts', to='core.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalengineers', to=settings.AUTH_USER_MODEL, verbose_name='Хэмжсэн инженер')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passportengineers', to=settings.AUTH_USER_MODEL, verbose_name='Хувийн хэрэг хөтөлсөн')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='core.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportengineers', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон')),
                ('measurements', models.ManyToManyField(related_name='reports', to='core.measurement')),
            ],
        ),
    ]
