# Generated by Django 5.1.5 on 2025-08-31 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_photo_options_remove_measurement_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='absolute_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='line',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Шугамын дугаар'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='relative_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='step',
            field=models.ManyToManyField(limit_choices_to={'key': 'MEASUREMENTSTEPS'}, related_name='steps', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='Acception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Тэмдэглэгдсэн')),
                ('accepted_by', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptors', to=settings.AUTH_USER_MODEL, verbose_name='Зөвшөөрсөн')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptions', to='core.measurement')),
                ('position', models.ForeignKey(blank=True, limit_choices_to={'key': 'POSITIONS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptpositions', to='core.constant', verbose_name='Төрөл')),
                ('step', models.ForeignKey(blank=True, limit_choices_to={'key': 'MEASUREMENTSTEPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptsteps', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
    ]
