# Generated by Django 5.1.5 on 2025-08-31 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_measurement_absolute_gravity_measurement_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'POINTSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countDate', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmers', to=settings.AUTH_USER_MODEL, verbose_name='Зөвшөөрсөн')),
                ('counted_by', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL, verbose_name='Зөвшөөрсөн')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.point')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'key': 'POINTSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countpoints', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.count'),
        ),
    ]
