# Generated by Django 5.1.5 on 2025-08-31 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_point_status_count_photo_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acception',
            name='position',
        ),
        migrations.AlterField(
            model_name='acception',
            name='step',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'STEPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptsteps', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='network',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEODETIC_NETWORK'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkpoints', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.point', verbose_name='Хэмжилт'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='step',
            field=models.ManyToManyField(limit_choices_to={'key': 'STEPS'}, related_name='steps', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'PHOTO_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phototypes', to='core.constant', verbose_name='Зургийн төрөл'),
        ),
        migrations.DeleteModel(
            name='BaseMap',
        ),
    ]
