# Generated by Django 5.1.5 on 2025-09-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_acception_position_alter_acception_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countphotos', to='core.count'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurementphotos', to='core.measurement', verbose_name='Цэг'),
        ),
        migrations.AlterField(
            model_name='point',
            name='center',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'CENTERTYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerlocations', to='core.constant', verbose_name='Төвийн хэлбэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'PROCESSSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
