# Generated by Django 5.1.5 on 2025-09-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_photo_count_alter_photo_measurement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='passport',
            new_name='act',
        ),
    ]
