# Generated by Django 5.1.5 on 2025-09-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_rename_passport_act_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='nomek',
            field=models.ManyToManyField(blank=True, related_name='nomekpoints', to='core.nomek', verbose_name='Нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='unitpoints', to='core.adminunit', verbose_name='Хил'),
        ),
    ]
