# Generated by Django 5.1.5 on 2025-09-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_point_nomek_alter_point_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='system',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEODETICSYSTEM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systempoints', to='core.constant'),
        ),
    ]
