# Generated by Django 5.1.5 on 2025-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_measurement_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='agreementId',
        ),
        migrations.CreateModel(
            name='Champaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementId', models.IntegerField(blank=True, null=True)),
                ('points', models.ManyToManyField(blank=True, related_name='champaignpoints', to='core.point', verbose_name='Хэмжилт')),
            ],
        ),
    ]
