# Generated by Django 5.1.5 on 2025-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_measurement_agreementid_champaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='projectId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Champaign',
        ),
    ]
