# Generated by Django 5.1.5 on 2025-09-01 14:28

import portal.utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_measurement_projectid_delete_champaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='journal',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path),
        ),
        migrations.AddField(
            model_name='measurement',
            name='journal_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalengineers', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path),
        ),
        migrations.AddField(
            model_name='measurement',
            name='passport_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passportengineers', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
