# Generated by Django 5.1.5 on 2025-09-02 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_passport_engineer_remove_passport_measurement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acception',
            old_name='accepted_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='act',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Зөвшөөрсөн'),
        ),
        migrations.AddField(
            model_name='act',
            name='officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to=settings.AUTH_USER_MODEL, verbose_name='Хүлээн авсан'),
        ),
        migrations.AlterField(
            model_name='acception',
            name='step',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'PROCESSSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptsteps', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
