# Generated by Django 5.1.5 on 2025-09-04 05:17

import portal.utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_rename_accepted_by_acception_user_act_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('amount', models.FloatField(default=1, verbose_name='Дүн')),
                ('vat', models.FloatField(default=0, verbose_name='Дүн')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гүйлгээний утга')),
                ('receiver', models.CharField(blank=True, null=True, verbose_name='Хүлээн авагчийн регистр')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлсөн')),
                ('invoice_id', models.CharField(blank=True, max_length=40, verbose_name='QPAY дугаар')),
                ('qp_qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('call_back', models.URLField(blank=True)),
                ('payment_id', models.CharField(blank=True, max_length=40, verbose_name='QPAY төлбөрийн дугаар')),
                ('wallet', models.CharField(blank=True, max_length=40, verbose_name='Төрөл')),
                ('ebarimt_id', models.CharField(blank=True, max_length=40, verbose_name='Ebarim дугаар')),
                ('ebarimt_bill_id', models.CharField(blank=True, max_length=200, verbose_name='ДДТД')),
                ('ebarimt_qr_data', models.CharField(blank=True, max_length=5000, verbose_name='Ebarimt data')),
                ('ebarimt_qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('ebarimt_lottery_id', models.CharField(blank=True, max_length=5000, verbose_name='Ebarimt сугалааны дугаар')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.point', verbose_name='QPAY банк')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'Гүйлгээ',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='QPAY дугаар')),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Дүн')),
                ('logo', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('link', models.CharField(blank=True, max_length=3000)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='core.payment', verbose_name='Банк')),
            ],
            options={
                'verbose_name_plural': 'Банк',
            },
        ),
        migrations.CreateModel(
            name='QpayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, null=True, verbose_name='type')),
                ('expire', models.CharField(blank=True, null=True, verbose_name='expire')),
                ('refresh_expire', models.CharField(blank=True, null=True, verbose_name='refresh expire')),
                ('refresh', models.CharField(blank=True, null=True, verbose_name='refresh')),
                ('access', models.CharField(blank=True, null=True, verbose_name='access')),
                ('scope', models.CharField(blank=True, null=True, verbose_name='scope')),
                ('session_state', models.CharField(blank=True, null=True, verbose_name='session_state')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.payment', verbose_name='Төлбөр')),
            ],
        ),
        migrations.DeleteModel(
            name='Acception',
        ),
    ]
