# Generated by Django 5.1.5 on 2025-09-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_payment_paymentbank_qpaytoken_delete_acception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Гүйлгээ'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='point',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vat',
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Хүлээн авагчийн регистр'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('ABANDONED', 'Abandoned')], default='OPEN', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('status', models.CharField(choices=[('PENDING', 'Төлөөгүй'), ('PAID', 'Төлсөн'), ('CANCELED', 'Цуцалсан'), ('FAILED', 'Алдаатай')], default='PENDING', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='core.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order', verbose_name='Захиалга'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.point')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('user',), name='uniq_open_cart_per_user'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='core_cartit_cart_id_c09971_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['point'], name='core_cartit_point_i_03d45a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'point')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'point')},
        ),
    ]
