# Generated by Django 5.1.5 on 2025-09-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_payment_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbank',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='core.payment', verbose_name='Банк'),
        ),
    ]
