# Generated by Django 5.1.5 on 2025-09-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_paymentbank_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminunit',
            old_name='centerName',
            new_name='centername',
        ),
    ]
