# Generated by Django 5.1.5 on 2025-09-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_rename_centername_adminunit_centername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkpoints', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
