# Generated by Django 5.1.5 on 2025-09-06 02:41

import portal.utils.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_workspace_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='workspace',
        ),
        migrations.AddField(
            model_name='feature',
            name='is_raster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='map',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Maps'),
        ),
        migrations.AddField(
            model_name='feature',
            name='pg_table',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace', verbose_name='feautes'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace', verbose_name='workspaces')),
            ],
        ),
    ]
