# Generated by Django 5.1.5 on 2025-09-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_feature_workspace_feature_is_raster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='feautes'),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='pg_table',
        ),
        migrations.AddField(
            model_name='feature',
            name='table',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GeomDatas'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featuretypes', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
