# Generated by Django 5.1.5 on 2025-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_feature_store_remove_feature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
