# Generated by Django 5.1.5 on 2025-09-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_feature_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='table',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GeomDatas'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
