# Generated by Django 5.1.5 on 2025-09-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_feature_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.constant', verbose_name='storefeautes'),
        ),
    ]
