# Generated by Django 5.1.5 on 2025-09-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_feature_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefeatures', to='core.constant'),
        ),
    ]
