# Generated by Django 5.1.5 on 2025-09-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_feature_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws', models.CharField(blank=True, max_length=40, verbose_name='Workspace')),
                ('column_name', models.CharField(blank=True, max_length=40, verbose_name='Group')),
                ('column_values', models.JSONField(blank=True, null=True)),
                ('style_name', models.CharField(blank=True, max_length=100)),
                ('color_ramp', models.CharField(default='tab20', max_length=40)),
                ('geom_type', models.CharField(default='polygon', max_length=16)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.feature', verbose_name='Layer')),
            ],
        ),
    ]
