# Generated by Django 5.1.5 on 2025-09-06 10:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='sld',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/monpos/geoserver/data_dir'), upload_to='', verbose_name='SLD'),
        ),
    ]
