# Generated by Django 5.1.5 on 2025-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_style_sld'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='cql',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
