# Generated by Django 5.1.5 on 2025-09-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_feature_cql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cql',
        ),
    ]
