# Generated by Django 5.1.5 on 2025-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_feature_cql'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='cql_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
