# Generated by Django 5.1.5 on 2025-09-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_feature_cql_filter_feature_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='layer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.feature', verbose_name='Layer'),
        ),
    ]
