# Generated by Django 5.1.5 on 2025-09-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_style_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layerOrder', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='style',
            name='layer',
        ),
        migrations.CreateModel(
            name='LayerGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='core.feature')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.layergroup')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_items', to='core.style')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='layergroup',
            name='layers',
            field=models.ManyToManyField(related_name='layer_groups', through='core.LayerGroupItem', to='core.feature'),
        ),
        migrations.CreateModel(
            name='StyleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cql_filter', models.TextField(blank=True)),
                ('min_scale_denom', models.BigIntegerField(blank=True, null=True)),
                ('max_scale_denom', models.BigIntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blend_mode', models.CharField(choices=[('normal', 'normal'), ('multiply', 'multiply'), ('screen', 'screen'), ('overlay', 'overlay'), ('darken', 'darken'), ('lighten', 'lighten')], default='normal', max_length=16)),
                ('symbolizer', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon'), ('raster', 'Raster'), ('text', 'Text')], default='polygon', max_length=16)),
                ('stroke_color', models.CharField(blank=True, max_length=32)),
                ('stroke_width', models.FloatField(blank=True, null=True)),
                ('stroke_opacity', models.FloatField(blank=True, null=True)),
                ('stroke_dasharray', models.CharField(blank=True, max_length=64)),
                ('stroke_linecap', models.CharField(blank=True, choices=[('butt', 'butt'), ('round', 'round'), ('square', 'square')], max_length=8)),
                ('stroke_linejoin', models.CharField(blank=True, choices=[('miter', 'miter'), ('round', 'round'), ('bevel', 'bevel')], max_length=8)),
                ('fill_color', models.CharField(blank=True, max_length=32)),
                ('fill_opacity', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('rotation', models.FloatField(blank=True, null=True)),
                ('text_field', models.CharField(blank=True, max_length=64)),
                ('text_size', models.FloatField(blank=True, null=True)),
                ('text_color', models.CharField(blank=True, max_length=32)),
                ('text_font_family', models.CharField(blank=True, max_length=64)),
                ('text_font_style', models.CharField(blank=True, max_length=16)),
                ('text_font_weight', models.CharField(blank=True, max_length=16)),
                ('text_halo_color', models.CharField(blank=True, max_length=32)),
                ('text_halo_radius', models.FloatField(blank=True, null=True)),
                ('text_anchor', models.CharField(blank=True, max_length=16)),
                ('text_displacement_x', models.FloatField(blank=True, null=True)),
                ('text_displacement_y', models.FloatField(blank=True, null=True)),
                ('text_rotation', models.FloatField(blank=True, null=True)),
                ('vendor_options', models.JSONField(blank=True, null=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.style')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='layergroupitem',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_items', to='core.stylerule'),
        ),
        migrations.AlterUniqueTogether(
            name='layergroupitem',
            unique_together={('group', 'feature', 'rule')},
        ),
    ]
