# Generated by Django 5.1.5 on 2025-09-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_layergroup_remove_style_layer_layergroupitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
