# Generated by Django 5.1.5 on 2025-09-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_feature_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cql_filter',
        ),
    ]
