# Generated by Django 5.1.5 on 2025-09-07 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_remove_feature_cql_filter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layergroupitem',
            unique_together={('group', 'feature')},
        ),
        migrations.AddField(
            model_name='style',
            name='layer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.feature', verbose_name='Layer'),
        ),
        migrations.RemoveField(
            model_name='layergroupitem',
            name='rule',
        ),
        migrations.DeleteModel(
            name='StyleRule',
        ),
    ]
