# Generated by Django 5.1.5 on 2025-09-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_layergroupitem_unique_together_style_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.feature', verbose_name='Layer'),
        ),
    ]
