# Generated by Django 5.1.5 on 2025-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_style_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='geom_type',
            field=models.CharField(blank=True, default='polygon', max_length=16, null=True),
        ),
    ]
