# Generated by Django 5.1.5 on 2025-09-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_stylerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldrules', to='core.constant'),
        ),
    ]
