# Generated by Django 5.1.5 on 2025-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_stylerule_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
