# Generated by Django 5.1.5 on 2025-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_stylerule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='ws',
        ),
        migrations.AddField(
            model_name='style',
            name='column',
            field=models.CharField(blank=True, max_length=40, verbose_name='column'),
        ),
    ]
