# Generated by Django 5.1.5 on 2025-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_style_ws_style_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='ws',
            field=models.CharField(blank=True, max_length=40, verbose_name='Workspace'),
        ),
    ]
