# Generated by Django 5.1.5 on 2025-09-09 04:58

import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_style_ws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sld',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='SLD'),
        ),
    ]
