# Generated by Django 5.1.5 on 2025-09-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_style_sld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sld',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/styles', verbose_name='SLD'),
        ),
    ]
