# Generated by Django 5.1.5 on 2025-09-09 05:42

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_style_sld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sld',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/monpos/geoserver/data_dir/styles'), upload_to=core.models.sld_upload_to, verbose_name='SLD'),
        ),
    ]
