# Generated by Django 5.1.5 on 2025-09-09 09:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_style_sld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sld',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(location='/var/monpos/geoserver/data_dir/workspaces'), upload_to=core.models.sld_upload_to, verbose_name='SLD'),
        ),
    ]
