# Generated by Django 5.1.5 on 2025-09-09 09:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_style_sld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massmail',
            name='counter',
        ),
        migrations.AddField(
            model_name='stylerule',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(location='/var/monpos/geoserver/data_dir/workspaces'), upload_to=core.models.sld_upload_to, verbose_name='SVG icon'),
        ),
    ]
