# Generated by Django 5.1.5 on 2025-09-09 10:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_remove_massmail_counter_stylerule_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(location='/var/monpos/geoserver/data_dir/workspaces'), upload_to=core.models.icon_upload_to, verbose_name='SVG icon'),
        ),
    ]
