# Generated by Django 5.1.5 on 2025-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_stylerule_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylerule',
            name='icon_url',
        ),
    ]
