# Generated by Django 5.1.5 on 2025-09-09 10:56

import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_remove_stylerule_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='SVG icon'),
        ),
    ]
