# Generated by Django 5.1.5 on 2025-09-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_stylerule_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylerule',
            options={'verbose_name': 'Таних'},
        ),
    ]
