# Generated by Django 5.1.5 on 2025-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_stylerule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/symbols', verbose_name='SVG icon'),
        ),
    ]
