# Generated by Django 5.1.5 on 2025-09-09 23:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_stylerule_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='core.measurement'),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to='upload_files/symbols', verbose_name='SVG icon'),
        ),
    ]
