# Generated by Django 5.1.5 on 2025-09-10 04:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_cartitem_point_alter_stylerule_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerunits', to='core.constant', verbose_name='UNIT_LEVEL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.admincenter', verbose_name='Харъяа')),
            ],
            options={
                'verbose_name_plural': 'Хил',
            },
        ),
    ]
