# Generated by Django 5.1.5 on 2025-09-10 04:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_admincenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincenter',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
