# Generated by Django 5.1.5 on 2025-09-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_alter_admincenter_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincenter',
            options={'verbose_name_plural': 'Center'},
        ),
    ]
