# Generated by Django 5.1.5 on 2025-09-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_admincenter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='journal',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/journal'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/passport'),
        ),
    ]
