# Generated by Django 5.1.5 on 2025-09-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_measurement_journal_alter_measurement_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='text_halo_opacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
