# Generated by Django 5.1.5 on 2025-09-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_stylerule_text_halo_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroupitem',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='layergroupitem',
            name='style',
        ),
        migrations.RemoveField(
            model_name='layergroupitem',
            name='z_index',
        ),
    ]
