# Generated by Django 5.1.5 on 2025-09-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_remove_layergroupitem_opacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layergroupitem',
            old_name='feature',
            new_name='layer',
        ),
        migrations.AlterUniqueTogether(
            name='layergroupitem',
            unique_together={('group', 'layer')},
        ),
    ]
