# Generated by Django 5.1.5 on 2025-09-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_rename_feature_layergroupitem_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='layerOrder',
        ),
        migrations.RemoveField(
            model_name='layergroup',
            name='layers',
        ),
    ]
