# Generated by Django 5.1.5 on 2025-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_layergroup_layerorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='is_width_text',
            field=models.BooleanField(default=False),
        ),
    ]
