# Generated by Django 5.1.5 on 2025-09-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_stylerule_is_width_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylerule',
            old_name='is_width_text',
            new_name='is_with_text',
        ),
    ]
