# Generated by Django 5.1.5 on 2025-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_rename_is_width_text_stylerule_is_with_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='text_field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
