# Generated by Django 5.1.5 on 2025-09-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_filter_stylerule_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(blank=True, limit_choices_to={'key': 'ROADSTATETYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadstates', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
    ]
