# Generated by Django 5.1.5 on 2025-09-13 04:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, default='un', max_length=2000, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='road',
            name='paver',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'ROADPAVETYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadpaves', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
