# Generated by Django 5.1.5 on 2025-09-13 05:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_road_geom_road_name_road_paver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylerule',
            name='cql_filter',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='field',
        ),
        migrations.AddField(
            model_name='road',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
