# Generated by Django 5.1.5 on 2025-09-13 08:44

import core.models
import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_remove_stylerule_cql_filter_remove_stylerule_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stylerule',
            options={'ordering': ['order', 'id'], 'verbose_name': 'SymbolRules'},
        ),
        migrations.RemoveField(
            model_name='style',
            name='color_ramp',
        ),
        migrations.RemoveField(
            model_name='style',
            name='column',
        ),
        migrations.RemoveField(
            model_name='style',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='style',
            name='column_values',
        ),
        migrations.AddField(
            model_name='filter',
            name='case_sensitive',
            field=models.BooleanField(default=True, help_text='LIKE үед ашиглаж болно'),
        ),
        migrations.AddField(
            model_name='filter',
            name='values_json',
            field=models.JSONField(blank=True, help_text="IN операторт зориулсан утгуудын жагсаалт (['289','290'])", null=True),
        ),
        migrations.AddField(
            model_name='stylerule',
            name='join_op',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(blank=True, help_text='PropertyName (талбарын нэр)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='operator',
            field=models.CharField(blank=True, choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('LIKE', 'LIKE'), ('IN', 'IN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.CharField(blank=True, help_text="Ихэнх операторт нэг утга. IN үед '289,290' гэх мэт CSV эсвэл values_json ашиглана.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='geom_type',
            field=models.CharField(blank=True, choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon'), ('raster', 'Raster')], default='polygon', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='fill_color',
            field=models.CharField(blank=True, max_length=32, validators=[core.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='fill_opacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='rules_legacy', to='core.filter'),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='max_scale_denom',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='min_scale_denom',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='name',
            field=models.CharField(blank=True, help_text='Легендийн нэр/эсвэл тоон ID-г Name-д ашиглаж болно', max_length=100),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='opacity',
            field=models.FloatField(default=1.0, help_text='0..1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Дүрмийн эрэмбэ (бага → түрүүнд)'),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='stroke_color',
            field=models.CharField(blank=True, max_length=32, validators=[core.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='stroke_opacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='text_color',
            field=models.CharField(blank=True, max_length=32, validators=[core.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='text_halo_color',
            field=models.CharField(blank=True, max_length=32, validators=[core.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='text_halo_opacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['is_published'], name='core_featur_is_publ_6511b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('layer', 'style_name'), name='uniq_style_per_layer'),
        ),
        migrations.AddField(
            model_name='rulefilter',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filter'),
        ),
        migrations.AddField(
            model_name='rulefilter',
            name='stylerule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stylerule'),
        ),
        migrations.AddField(
            model_name='stylerule',
            name='filters_new',
            field=models.ManyToManyField(blank=True, related_name='rules', to='core.filter'),
        ),
        migrations.AddIndex(
            model_name='stylerule',
            index=models.Index(fields=['style', 'order'], name='core_styler_style_i_91b573_idx'),
        ),
        migrations.AddIndex(
            model_name='stylerule',
            index=models.Index(fields=['is_visible'], name='core_styler_is_visi_a8b522_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rulefilter',
            unique_together={('stylerule', 'filter', 'position')},
        ),
    ]
