# Generated by Django 5.1.5 on 2025-09-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_move_filters_to_rulefilter'),
    ]

    operations = [
        # 1) Хуучин M2M талбарыг устгана
        migrations.RemoveField(
            model_name="stylerule",
            name="filters",
        ),
        # 2) filters_new-ийг filters болгон rename
        migrations.RenameField(
            model_name="stylerule",
            old_name="filters_new",
            new_name="filters",
        ),
    ]
