# Generated by Django 5.1.5 on 2025-09-14 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_remove_stylerule_filters_new_alter_stylerule_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='count',
        ),
        migrations.CreateModel(
            name='ReCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Тайлбар')),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmers', to=settings.AUTH_USER_MODEL, verbose_name='Зөвшөөрсөн')),
                ('counted_by', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL, verbose_name='Зөвшөөрсөн')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.point')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'key': 'POINTSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countpoints', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='recount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countphotos', to='core.recount'),
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
