# Generated by Django 5.1.5 on 2025-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_remove_photo_count_recount_photo_recount_and_more'),
    ]

    operations = [
 
        migrations.DeleteModel(
            name='RuleFilter',
        ),
    ]
