# Generated by Django 5.1.5 on 2025-09-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_alter_stylerule_filters_delete_rulefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='rules', to='core.filter'),
        ),
    ]
