# Generated by Django 5.1.5 on 2025-09-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_alter_stylerule_filters'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='style',
            name='uniq_style_per_layer',
        ),
    ]
