# Generated by Django 5.1.5 on 2025-09-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_remove_style_uniq_style_per_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylerule',
            name='filters',
        ),
    ]
