# Generated by Django 5.1.5 on 2025-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_remove_stylerule_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='rules', to='core.filter'),
        ),
    ]
