# Generated by Django 5.1.5 on 2025-09-14 08:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_alter_stylerule_stroke_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='fill_color',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[core.models.validate_hex_color]),
        ),
    ]
