# Generated by Django 5.1.5 on 2025-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_alter_stylerule_fill_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylerule',
            name='filters',
        ),
        migrations.AddField(
            model_name='stylerule',
            name='filters',
            field=models.JSONField(blank=True, help_text='[{field, operator, value}] хэлбэртэй JSON', null=True),
        ),
    ]
