# Generated by Django 5.1.5 on 2025-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_remove_stylerule_filters_stylerule_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylerule',
            name='stroke_dasharray',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
