# Generated by Django 5.1.5 on 2025-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_alter_stylerule_stroke_dasharray'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='rulename',
            field=models.CharField(blank=True, help_text='Дүрмийн нэр', max_length=100),
        ),
    ]
