# Generated by Django 5.1.5 on 2025-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_stylerule_rulename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField()),
                ('user_hash', models.CharField(max_length=64)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user_query_raw', models.TextField()),
                ('normalized_query', models.TextField(blank=True, null=True)),
                ('predicted_intent', models.CharField(blank=True, max_length=64, null=True)),
                ('predicted_slots', models.JSONField(blank=True, default=dict)),
                ('routing', models.CharField(max_length=32)),
                ('context_sources', models.JSONField(blank=True, default=list)),
                ('bot_response_text', models.TextField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('thumb', models.SmallIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('gold_intent', models.CharField(blank=True, max_length=64, null=True)),
                ('gold_slots', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
