# Generated by Django 5.1.5 on 2025-09-17 00:04

import portal.utils.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_chatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Maps')),
                ('is_raster', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, max_length=3000, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('geom_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='store',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='table',
        ),
        migrations.RemoveField(
            model_name='style',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='style',
        ),
        migrations.RemoveIndex(
            model_name='stylerule',
            name='core_styler_style_i_91b573_idx',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='rulename',
        ),
        migrations.AddField(
            model_name='layer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefeatures', to='core.constant'),
        ),
        migrations.AddField(
            model_name='layer',
            name='table',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GeomDatas'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='layer',
            name='ws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wsfeatures', to='core.constant'),
        ),
        migrations.AddField(
            model_name='stylerule',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.layer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layergroupitem',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='core.layer'),
        ),
        migrations.AddIndex(
            model_name='stylerule',
            index=models.Index(fields=['layer', 'order'], name='core_styler_layer_i_0ffd44_idx'),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['is_published'], name='core_layer_is_publ_02fdf1_idx'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
