# Generated by Django 5.1.5 on 2025-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_layer_remove_feature_store_remove_feature_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylerule',
            name='is_text_rule',
            field=models.BooleanField(default=False),
        ),
    ]
