# Generated by Django 5.1.5 on 2025-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_stylerule_is_text_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylerule',
            name='is_text_rule',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='is_with_text',
        ),
        migrations.AddField(
            model_name='stylerule',
            name='render_mode',
            field=models.CharField(blank=True, default='symbol', max_length=16),
        ),
    ]
