# Generated by Django 5.1.5 on 2025-09-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ForeignKey(blank=True, default=166, limit_choices_to={'key': 'POINTSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
