# Generated by Django 5.1.5 on 2025-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_alter_point_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='counter'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Төлбөр'),
        ),
    ]
