# Generated by Django 5.1.5 on 2025-09-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_payment_counter_payment_is_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='uniq_open_cart_per_user',
        ),
    
    ]
