# Generated by Django 5.1.5 on 2025-09-20 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_remove_cart_uniq_open_cart_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'CARTSTATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
