# Generated by Django 5.1.5 on 2025-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='catalogy',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/payment/catalogy'),
        ),
    ]
