# Generated by Django 5.1.5 on 2025-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_cartitem_catalogy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='catalogy',
        ),
        migrations.AddField(
            model_name='cart',
            name='catalogy',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/payment/catalogy'),
        ),
    ]
