# Generated by Django 5.1.5 on 2025-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_remove_cartitem_catalogy_cart_catalogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='inquire_qr',
            field=models.ImageField(blank=True, null=True, upload_to='upload_files/payment/qr'),
        ),
        migrations.AddField(
            model_name='cart',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
