# Generated by Django 5.1.5 on 2025-09-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_cart_inquire_qr_cart_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cart', verbose_name='Захиалга'),
        ),
    ]
