# Generated by Django 5.1.5 on 2025-09-23 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='sso_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
