# Generated by Django 5.1.5 on 2025-09-26 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_alter_remoteuser_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.measurement'),
        ),
    ]
