# Generated by Django 5.1.5 on 2025-09-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_alter_cartitem_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteuser',
            name='sso_user_id',
        ),
    ]
