# Generated by Django 5.1.5 on 2025-09-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_remove_remoteuser_sso_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дүн'),
            preserve_default=False,
        ),
    ]
