# Generated by Django 5.1.5 on 2025-10-23 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NlExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('py_func', 'Python function'), ('orm', 'Django ORM'), ('endpoint', 'HTTP API')], default='py_func', max_length=20)),
                ('handler_path', models.CharField(blank=True, max_length=200)),
                ('orm_model', models.CharField(blank=True, max_length=200)),
                ('filter_template', models.JSONField(blank=True, default=dict)),
                ('order_by', models.JSONField(blank=True, default=list)),
                ('values_list', models.JSONField(blank=True, default=list)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('url_template', models.CharField(blank=True, max_length=400)),
                ('method', models.CharField(default='GET', max_length=6)),
                ('payload_template', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NlIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='NlResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80)),
                ('render_type', models.CharField(default='rendered', max_length=20)),
                ('template', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.nlintent')),
            ],
            options={
                'unique_together': {('intent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NlSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(default='text', max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.nlintent')),
            ],
            options={
                'unique_together': {('intent', 'key')},
            },
        ),
        migrations.RemoveField(
            model_name='massmail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='nlexecutor',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='core.nlintent'),
        ),
        migrations.DeleteModel(
            name='MassMail',
        ),
    ]
