# Generated by Django 5.1.5 on 2025-10-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_nlexecutor_nlintent_nlresponsetemplate_nlslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(default='', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Executor backend',
                'verbose_name_plural': 'Executor backends',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=8, unique=True)),
                ('label', models.CharField(default='', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Locale',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='NlIntentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_key', models.SlugField(max_length=80)),
                ('priority', models.IntegerField(default=100)),
                ('require_any_tokens', models.JSONField(blank=True, default=list)),
                ('require_all_tokens', models.JSONField(blank=True, default=list)),
                ('forbid_tokens', models.JSONField(blank=True, default=list)),
                ('require_slots_any', models.JSONField(blank=True, default=list)),
                ('require_slots_all', models.JSONField(blank=True, default=list)),
                ('forbid_slots', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NlParserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('today_override', models.DateField(blank=True, null=True)),
                ('default_radius_m', models.PositiveIntegerField(default=2000)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NlTokenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegexFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=2, unique=True)),
                ('label', models.CharField(default='', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regex flag',
                'verbose_name_plural': 'Regex flags',
            },
        ),
        migrations.CreateModel(
            name='RegexKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regex kind',
                'verbose_name_plural': 'Regex kinds',
            },
        ),
        migrations.CreateModel(
            name='ResolverRegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rule_type', models.CharField(choices=[('boundary', 'Boundary'), ('normalizer', 'Normalizer')], default='boundary', max_length=20)),
                ('pattern', models.CharField(max_length=500)),
                ('replace', models.CharField(blank=True, default='', max_length=200)),
                ('priority', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resolver regex rule',
                'verbose_name_plural': 'Resolver regex rules',
            },
        ),
        
        migrations.CreateModel(
            name='LevelPreferenceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('regex', models.CharField(max_length=400)),
                ('level_order', models.JSONField(default=list)),
                ('weight_step', models.IntegerField(default=12)),
                ('enabled', models.BooleanField(default=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_pref_keywords', to='core.locale')),
            ],
            options={
                'verbose_name': 'Level preference keyword',
                'verbose_name_plural': 'Level preference keywords',
            },
        ),
        migrations.CreateModel(
            name='AdminAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canon_name', models.CharField(db_index=True, max_length=200)),
                ('variant', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=100, help_text='Alias boost score.')),
                ('enabled', models.BooleanField(default=True)),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='core.adminunit')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_aliases', to='core.locale')),
            ],
            options={
                'verbose_name': 'Admin alias',
                'verbose_name_plural': 'Admin aliases',
            },
        ),
        migrations.CreateModel(
            name='NlToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('regex', models.BooleanField(default=False)),
                ('flags', models.CharField(blank=True, default='', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.nltokengroup')),
            ],
        ),
        migrations.CreateModel(
            name='NlRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('pattern', models.TextField()),
                ('priority', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('flags', models.ManyToManyField(blank=True, related_name='regexes', to='core.regexflag')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regexes', to='core.regexkind')),
            ],
        ),
        migrations.CreateModel(
            name='ResolverTokenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('letter_class', models.CharField(default='A-Za-zА-Яа-яӨөҮүЁё', help_text='Үсгийн ангилалд орох зөвшөөрөгдсөн тэмдэгтүүдийн класс (regex fragment).', max_length=300)),
                ('split_pattern', models.CharField(default='[^\\wA-Za-zА-Яа-яӨөҮүЁё\\-]+', help_text='Токен салгах regex.', max_length=300)),
                ('suffix_pattern', models.CharField(default='(?:ын|ийн|ны|гийн|гын|аас|ээс|оос|өөс|руу|рүү|тай|тэй|хооронд|дотроос|[оөуае]?(?:д|т))$', help_text='Төгсгөлийн дагаваруудыг таних regex.', max_length=500)),
                ('level_word_pattern', models.CharField(default='\\b(аймаг|нийслэл|хот|сум|дүүрэг|баг|хороо)(?:[оөуае]?(?:д|т)|(?:ын|ийн|ны|гийн|гын)|(?:руу|рүү)|(?:оор|ээр))?\\b', help_text='Аймаг/сум/дүүрэг ... зэрэг түвшний түлхүүрүүдийн regex.', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolver_configs', to='core.locale')),
            ],
            options={
                'verbose_name': 'Resolver token config',
                'verbose_name_plural': 'Resolver token configs',
            },
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stopwords', to='core.locale')),
            ],
            options={
                'verbose_name': 'Stopword',
                'verbose_name_plural': 'Stopwords',
            },
        ),
    ]
