# Generated by Django 5.1.5 on 2025-10-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_executorbackend_locale_nlintentrule_nlparserconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nlexecutor',
            options={'verbose_name': 'NL Executor', 'verbose_name_plural': 'NL Executors'},
        ),
        migrations.AlterModelOptions(
            name='nlintent',
            options={'verbose_name': 'NL Intent', 'verbose_name_plural': 'NL Intents'},
        ),
        migrations.AlterModelOptions(
            name='nlresponsetemplate',
            options={'verbose_name': 'NL Response template', 'verbose_name_plural': 'NL Response templates'},
        ),
        migrations.AlterModelOptions(
            name='nlslot',
            options={'verbose_name': 'NL Slot', 'verbose_name_plural': 'NL Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='nlresponsetemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nlslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nlexecutor',
            name='backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='core.executorbackend'),
        ),
        migrations.AlterField(
            model_name='nlslot',
            name='data_type',
            field=models.CharField(default='text', help_text='text/number/date/datetime/geo/json', max_length=20),
        ),
    ]
