# Generated by Django 5.1.5 on 2025-10-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_alter_nlexecutor_options_alter_nlintent_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelPreferenceKeyword',
            new_name='NlLevelPreferenceKeyword',
        ),
        migrations.RenameModel(
            old_name='ResolverRegexRule',
            new_name='NlResolverRegexRule',
        ),
    ]
