# Generated by Django 5.1.5 on 2025-10-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_rename_levelpreferencekeyword_nllevelpreferencekeyword_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAlias',
            new_name='NlAdminAlias',
        ),
        migrations.RenameModel(
            old_name='ResolverTokenConfig',
            new_name='NlResolverTokenConfig',
        ),
        migrations.RenameModel(
            old_name='Stopword',
            new_name='NlStopword',
        ),
    ]
