# Generated by Django 5.1.5 on 2025-10-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_rename_adminalias_nladminalias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegexFlag',
            new_name='NlRegexFlag',
        ),
        migrations.RenameModel(
            old_name='RegexKind',
            new_name='NlRegexKind',
        ),
    ]
