# Generated by Django 5.1.5 on 2025-10-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_rename_regexflag_nlregexflag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExecutorBackend',
            new_name='NlExecutorBackend',
        ),
        migrations.RenameModel(
            old_name='Locale',
            new_name='NlLocale',
        ),
    ]
