# Generated by Django 5.1.5 on 2025-10-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_rename_executorbackend_nlexecutorbackend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nladminalias',
            name='admin_unit',
        ),
        migrations.RemoveField(
            model_name='nladminalias',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='nlexecutor',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='nlexecutor',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='nlresponsetemplate',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='nlslot',
            name='intent',
        ),
        migrations.DeleteModel(
            name='NlIntentRule',
        ),
        migrations.RemoveField(
            model_name='nllevelpreferencekeyword',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='nlresolvertokenconfig',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='nlstopword',
            name='locale',
        ),
        migrations.DeleteModel(
            name='NlParserConfig',
        ),
        migrations.RemoveField(
            model_name='nlregex',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='nlregex',
            name='kind',
        ),
        migrations.DeleteModel(
            name='NlResolverRegexRule',
        ),
        migrations.RemoveField(
            model_name='nltoken',
            name='group',
        ),
        migrations.DeleteModel(
            name='NlAdminAlias',
        ),
        migrations.DeleteModel(
            name='NlExecutorBackend',
        ),
        migrations.DeleteModel(
            name='NlExecutor',
        ),
        migrations.DeleteModel(
            name='NlResponseTemplate',
        ),
        migrations.DeleteModel(
            name='NlIntent',
        ),
        migrations.DeleteModel(
            name='NlSlot',
        ),
        migrations.DeleteModel(
            name='NlLevelPreferenceKeyword',
        ),
        migrations.DeleteModel(
            name='NlResolverTokenConfig',
        ),
        migrations.DeleteModel(
            name='NlLocale',
        ),
        migrations.DeleteModel(
            name='NlStopword',
        ),
        migrations.DeleteModel(
            name='NlRegexFlag',
        ),
        migrations.DeleteModel(
            name='NlRegex',
        ),
        migrations.DeleteModel(
            name='NlRegexKind',
        ),
        migrations.DeleteModel(
            name='NlToken',
        ),
        migrations.DeleteModel(
            name='NlTokenGroup',
        ),
    ]
