# Generated by Django 5.1.5 on 2025-10-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0182_remove_nladminalias_admin_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NL Type',
                'verbose_name_plural': 'NL Types',
            },
        ),
        migrations.CreateModel(
            name='NLEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.nlentity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.nltype')),
            ],
        ),
        migrations.CreateModel(
            name='NLAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('norm', models.CharField(db_index=True, max_length=512)),
                ('lang', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('is_regex', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.nlentity')),
            ],
            options={
                'unique_together': {('entity', 'norm')},
            },
        ),
    ]
