# Generated by Django 5.1.5 on 2025-10-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_nltype_nlentity_nlalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NL Intent',
                'verbose_name_plural': 'NL Intents',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NLQueryPlanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_query', models.TextField()),
                ('slots', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('debug', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='core.nlintent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NL Query Plan Log',
                'verbose_name_plural': 'NL Query Plan Logs',
            },
        ),
    ]
