# Generated by Django 5.1.5 on 2025-10-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_nlintent_nlqueryplanlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlentity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nlentity',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='nlentity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='nlqueryplanlog',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='nlqueryplanlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='NLAlias',
        ),
        migrations.DeleteModel(
            name='NLEntity',
        ),
        migrations.DeleteModel(
            name='NLType',
        ),
        migrations.DeleteModel(
            name='NLIntent',
        ),
        migrations.DeleteModel(
            name='NLQueryPlanLog',
        ),
    ]
