# Generated by Django 5.1.5 on 2025-10-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_remove_nlentity_content_type_remove_nlentity_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.adminunit', verbose_name='Хил'),
        ),
    ]
