# Generated by Django 5.1.5 on 2025-10-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_role_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='unit',
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.adminunit', verbose_name='Хил'),
        ),
    ]
