# Generated by Django 5.1.5 on 2025-10-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_remove_role_unit_remoteuser_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedunits', to='core.adminunit', verbose_name='Хил'),
        ),
    ]
