# Generated by Django 5.1.5 on 2025-10-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_alter_remoteuser_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='core.measurement'),
        ),
        migrations.AlterField(
            model_name='act',
            name='measurements',
            field=models.ManyToManyField(to='core.measurement'),
        ),
    ]
