# Generated by Django 5.1.5 on 2025-10-27 15:33

import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_act_accepted_date_act_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='link',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path),
        ),
    ]
