# Generated by Django 5.1.5 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_act_link_act_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='qr_data',
            field=models.CharField(blank=True, max_length=5000, verbose_name='QR data'),
        ),
    ]
