# Generated by Django 5.1.5 on 2025-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_act_qr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
