# Generated by Django 5.1.5 on 2025-10-28 09:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_act_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('str', 'str'), ('int', 'int'), ('date', 'date'), ('json', 'json')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(db_index=True, max_length=200)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='GazetteerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='any', max_length=50)),
                ('min_score', models.FloatField(default=0.3)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gazetteer_links', to='core.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('bot', 'bot')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.intent')),
            ],
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=500)),
                ('flags', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regex_rules', to='core.slottype')),
            ],
            options={
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IntentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_slots', to='core.intent')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_intents', to='core.slottype')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('slots_json', models.JSONField(default=dict)),
                ('locale', models.CharField(default='mn', max_length=10)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.intent')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=200)),
                ('weight', models.FloatField(default=1.0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.entity')),
            ],
            options={
                'unique_together': {('entity', 'text')},
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['canonical'], name='core_entity_canonic_769b2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('type', 'canonical')},
        ),
        migrations.AlterUniqueTogether(
            name='responsetemplate',
            unique_together={('intent', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='intentslot',
            unique_together={('intent', 'slot')},
        ),
        migrations.AddIndex(
            model_name='trainingutterance',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='core_traini_sv_ea42b2_gin'),
        ),
    ]
