# Generated by Django 5.1.5 on 2025-10-29 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_conversation_entitytype_intent_slottype_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(blank=True, limit_choices_to={'level': 'null'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='core.adminunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
