# Generated by Django 5.1.5 on 2025-10-29 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='network',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEODETIC_NETWORK'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='core.constant'),
        ),
    ]
