# Generated by Django 5.1.5 on 2025-10-29 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_number_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 284}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='core.adminunit'),
        ),
    ]
