# Generated by Django 5.1.5 on 2025-10-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_alter_number_name_alter_number_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.measurement'),
        ),
    ]
