# Generated by Django 5.1.5 on 2025-10-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_measurement_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='x_ref',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='y_ref',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='z_ref',
        ),
    ]
