# Generated by Django 5.1.5 on 2025-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_remove_measurement_x_ref_remove_measurement_y_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mongeoid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('b', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('dh', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'mongeoid',
                'managed': False,
            },
        ),
    ]
