# Generated by Django 5.1.5 on 2025-11-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_mongeoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M1000',
        ),
        migrations.DeleteModel(
            name='M10000',
        ),
        migrations.DeleteModel(
            name='M100000',
        ),
        migrations.DeleteModel(
            name='M2000',
        ),
        migrations.DeleteModel(
            name='M25000',
        ),
        migrations.DeleteModel(
            name='M5000',
        ),
        migrations.DeleteModel(
            name='M50000',
        ),
        migrations.RemoveField(
            model_name='system',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='system',
            name='epoch',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        migrations.AddField(
            model_name='measurement',
            name='org',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
