# Generated by Django 5.1.5 on 2025-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_delete_m1000_delete_m10000_delete_m100000_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='monposId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
