# Generated by Django 5.1.5 on 2025-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_measurement_monposid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, verbose_name='Хандалт')),
                ('line', models.CharField(blank=True, max_length=400, null=True, verbose_name='Шугамын дугаар')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Байршлын тэмдэглэл')),
                ('final_x', models.FloatField(blank=True, null=True, verbose_name='Бодсон X')),
                ('final_y', models.FloatField(blank=True, null=True, verbose_name='Бодсон Y')),
                ('final_z', models.FloatField(blank=True, null=True, verbose_name='Бодсон Z')),
                ('horht', models.FloatField(blank=True, null=True)),
                ('relative_gravity', models.FloatField(blank=True, null=True)),
                ('absolute_gravity', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(blank=True, default=True, null=True, verbose_name='Шинээр суулгасан')),
                ('measured_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mongeoid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('b', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('company', models.IntegerField(blank=True, db_column='company', null=True)),
                ('ell', models.DecimalField(blank=True, db_column='ell', decimal_places=3, max_digits=10, null=True)),
                ('ortho', models.DecimalField(blank=True, db_column='orth', decimal_places=3, max_digits=10, null=True)),
                ('network', models.DecimalField(blank=True, db_column='class', decimal_places=3, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
            ],
            options={
                'db_table': 'mongeoid',
                'managed': False,
            },
        ),
    ]
