# Generated by Django 5.1.5 on 2025-11-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_oldmeasurement_oldpoint'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oldpoint',
            table='old',
        ),
    ]
