# Generated by Django 5.1.5 on 2025-11-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_alter_oldpoint_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldMeasurement',
        ),
    ]
