# Generated by Django 5.1.5 on 2025-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_delete_oldmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='userpermissions', to='core.role'),
        ),
    ]
