# Generated by Django 5.1.13 on 2025-11-17 03:09

import portal.utils.photoutils
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_remoteuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='views',
            field=models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='code',
            field=models.CharField(blank=True, help_text='Тогтмолын код.', max_length=1000, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='color',
            field=models.CharField(blank=True, help_text='HEX форматын өнгөний код.', max_length=1000, null=True, verbose_name='Өнгө'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='desc',
            field=models.CharField(blank=True, help_text='Тогтмолын дэлгэрэнгүй тайлбар.', max_length=5000, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='key',
            field=models.CharField(blank=True, help_text='Тогтмолын бүлгийг илэрхийлэх түлхүүр утга.', max_length=1000, null=True, verbose_name='Түлхүүр'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='label',
            field=models.CharField(blank=True, help_text='Хэрэглэгчид харагдах товч нэр.', max_length=1000, null=True, verbose_name='Харуулах нэр'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='name',
            field=models.CharField(blank=True, help_text='Тогтмолын нэр.', max_length=1000, null=True, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='absolute_gravity',
            field=models.FloatField(blank=True, help_text='Абсолют хүндийн хүчний хэмжилтийн утга.', null=True, verbose_name='Абсолют хүндийн хүч'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='description',
            field=models.CharField(blank=True, help_text='Цэгийн байршлын дэлгэрэнгүй тэмдэглэл.', max_length=400, null=True, verbose_name='Байршлын тэмдэглэл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='deviceId',
            field=models.IntegerField(blank=True, help_text='Хэмжилт хийсэн төхөөрөмжийн дугаар.', null=True, verbose_name='Төхөөрөмжийн дугаар'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='final_x',
            field=models.FloatField(blank=True, help_text='Тэгшитгэн бодсон X координат.', null=True, verbose_name='Бодсон X'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='final_y',
            field=models.FloatField(blank=True, help_text='Тэгшитгэн бодсон Y координат.', null=True, verbose_name='Бодсон Y'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='final_z',
            field=models.FloatField(blank=True, help_text='Тэгшитгэн бодсон Z координат.', null=True, verbose_name='Бодсон Z'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='horht',
            field=models.FloatField(blank=True, help_text='Ортометрын өндөр эсвэл түүний зөрүү (системээс хамаарна).', null=True, verbose_name='Ортометрын өндрийн зөрүү'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, help_text='Цэг шинээр суулгасан эсэх.', null=True, verbose_name='Шинээр суулгасан'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='journal',
            field=models.FileField(blank=True, help_text='Хэмжилтийн тэгшитгэлийн журнал файл.', null=True, upload_to='upload_files/journal', verbose_name='Тэгшитгэлийн журнал'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='journal_engineer',
            field=models.ForeignKey(blank=True, help_text='Журналын тэгшитгэлийг хийсэн инженер.', limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalengineers', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='line',
            field=models.CharField(blank=True, help_text='Хэмжилтийн шугамын дугаар.', max_length=400, null=True, verbose_name='Шугамын дугаар'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measured_date',
            field=models.DateTimeField(blank=True, help_text='Хэмжилт хийсэн огноо, цаг.', null=True, verbose_name='Хэмжилт хийсэн огноо'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='monposId',
            field=models.IntegerField(blank=True, help_text='MonPos систем дэх холбогдох дугаар.', null=True, verbose_name='MonPos дугаар'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='network',
            field=models.ForeignKey(blank=True, help_text='Хэмжилтийн сүлжээний төрөл.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkpoints', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Тэгшитгэлийг хийсэн байгууллага.', limit_choices_to={'is_citizen': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Эцэг хэмжилтийн бичлэг.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.measurement', verbose_name='Эцэг хэмжилт'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='passport',
            field=models.FileField(blank=True, help_text='Цэгийн паспортыг агуулсан файл.', null=True, upload_to='upload_files/passport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='passport_engineer',
            field=models.ForeignKey(blank=True, help_text='Паспорт бэлтгэсэн инженер.', limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passportengineers', to=settings.AUTH_USER_MODEL, verbose_name='Тэгшитгэн бодсон'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='point',
            field=models.ForeignKey(blank=True, help_text='Хэмжилт хамаарах цэг.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.point', verbose_name='Хэмжилт'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='projectId',
            field=models.IntegerField(blank=True, help_text='Хэмжилт хамаарах төслийн дугаар.', null=True, verbose_name='Төсөл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='relative_gravity',
            field=models.FloatField(blank=True, help_text='Харьцангуй хүндийн хүчний хэмжилтийн утга.', null=True, verbose_name='Харьцангуй хүндийн хүч'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='step',
            field=models.ManyToManyField(help_text='Хэмжилтийн үе шат, алхамууд (зөвхөн админаар шинэчлэгдэнэ).', limit_choices_to={'key': 'STEPS'}, related_name='steps', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='system',
            field=models.ForeignKey(blank=True, help_text='Хэмжилт хийсэн геодезийн координатын тогтолцоо.', limit_choices_to={'key': 'GEODETICSYSTEM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systempoints', to='core.constant', verbose_name='Геодезийн тогтолцоо'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Нэрлэврийн төлөөлөх төв цэг.', null=True, srid=4326, verbose_name='Төв цэг'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Нэрлэврийн хил, геометр.', null=True, srid=4326, verbose_name='Хил'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='Энэ нэрлэвэр газрын зураг дээр тэмдэглэгдсэн эсэх.', verbose_name='Газрын зурагт тэмдэглэсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='nomek',
            field=models.CharField(blank=True, help_text='Нэрлэврийн код эсвэл нэр.', max_length=25, null=True, verbose_name='Нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Дээд шатны нэрлэвэр.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.nomek', verbose_name='Дээд нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='scale',
            field=models.ForeignKey(blank=True, help_text='Нэрлэврийн зураглалын масштаб.', limit_choices_to={'key': 'MAPSCALES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='views',
            field=models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт'),
        ),
        migrations.AlterField(
            model_name='point',
            name='center',
            field=models.ForeignKey(blank=True, help_text='Цэгийн төвийн хэлбэрийн төрөл.', limit_choices_to={'key': 'CENTERTYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerlocations', to='core.constant', verbose_name='Төвийн хэлбэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='point',
            name='geoloc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Цэгийн газарзүйн координат (WGS84).', null=True, srid=4326, verbose_name='Газарзүйн байрлал'),
        ),
        migrations.AlterField(
            model_name='point',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн'),
        ),
        migrations.AlterField(
            model_name='point',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, help_text='Цэгийн албан ёсны нэр.', max_length=1000, null=True, verbose_name='Цэгийн нэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='nomek',
            field=models.ManyToManyField(blank=True, help_text='Энэ цэг хамаарах нэрлэвэр(үүд).', related_name='nomekpoints', to='core.nomek', verbose_name='Нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='number',
            field=models.CharField(blank=True, help_text='Системийн эсвэл сүлжээний цэгийн дугаар.', max_length=1000, null=True, verbose_name='Цэгийн дугаар'),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ForeignKey(default=166, help_text='Цэгийн төлөв (идэвхтэй, устгасан гэх мэт).', limit_choices_to={'key': 'POINTSTATUS'}, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='point',
            name='unit',
            field=models.ManyToManyField(blank=True, help_text='Цэг байрлах захиргааны нэгжийн хил.', related_name='unitpoints', to='core.adminunit', verbose_name='Хил'),
        ),
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн'),
        ),
        migrations.AlterField(
            model_name='point',
            name='views',
            field=models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Хэрэглэгчийн имэйл хаяг.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='first_name',
            field=models.CharField(help_text='Хэрэглэгчийн өөрийн нэр.', max_length=100, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='is_citizen',
            field=models.BooleanField(default=False, help_text='Иргэн эсэхийг илэрхийлнэ. Иргэн бол үнэн (True).', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='last_name',
            field=models.CharField(help_text='Хэрэглэгчийн овог.', max_length=100, verbose_name='Овог'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Холбоо барих утасны дугаар.', max_length=50, null=True, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='Хэрэглэгчийн зураг эсвэл лого.', null=True, upload_to=portal.utils.photoutils.get_profile_photo_upload_path, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='register',
            field=models.CharField(error_messages={'unique': 'Регистр бүртгэгдсэн байна'}, help_text='Иргэн эсвэл байгууллагын регистрийн дугаар.', max_length=30, unique=True, verbose_name='Регистр'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Хэрэглэгчийн үндсэн эрх.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='Эрх'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Хэрэглэгчид ногдох нэмэлт эрхүүд.', null=True, related_name='userpermissions', to='core.role', verbose_name='Нэмэлт эрхүүд'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='sso_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Төвлөрсөн нэвтрэлтийн SSO дугаар.', unique=True, verbose_name='SSO дугаар'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Харьяалагдах захиргааны нэгж.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedunits', to='core.adminunit', verbose_name='Хил'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(help_text='Энэ эрхээр зөвшөөрөгдөх тогтмол/үйлдлүүд.', related_name='permissions', to='core.constant', verbose_name='Зөвшөөрөгдөх үйлдлүүд'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Эрхийн нэр.', max_length=160, verbose_name='Нэр'),
        ),
    ]
