# Generated by Django 5.1.13 on 2025-11-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_alter_cart_created_date_alter_cart_last_view_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constant',
            options={'ordering': ['key'], 'verbose_name': 'Constant', 'verbose_name_plural': 'Системийн Тогтмол'},
        ),
        migrations.AlterField(
            model_name='constant',
            name='color',
            field=models.CharField(blank=True, help_text='Форматын өнгөний код.', max_length=1000, null=True, verbose_name='Өнгө'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='desc',
            field=models.CharField(blank=True, help_text='Дэлгэрэнгүй тайлбар, зарим тохиолдолд front хуудасны зам', max_length=5000, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Харъяалагдах тогтмол', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.constant'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='data',
            field=models.TextField(null=True, verbose_name='Body data'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='method',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Дуудсан method'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='params'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='remote_ip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Хэрэглэгчийн IP'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='scheme',
            field=models.TextField(null=True, verbose_name='Header scheme'),
        ),
        migrations.AlterField(
            model_name='error500',
            name='url',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Хандсан URL'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Алдааны код'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=models.TextField(null=True, verbose_name='Body data'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='method',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Дуудсан method'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='Params'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='remote_ip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Хэрэглэгчийн IP'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='url',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Хандсан URL'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Request body'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_index=True, max_length=10, verbose_name='Дуудсан Method'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='Params'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Хариултын төлөв'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='url',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Хандсан URL'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Хэрэглэгчийн эрх.', max_length=160, verbose_name='Нэр'),
        ),
    ]
