# Generated by Django 5.1.13 on 2025-11-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_alter_constant_options_alter_constant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Харъяалагдах тогтмол', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.constant', verbose_name='Харъяалагдах тогтмол'),
        ),
    ]
