# Generated by Django 5.1.13 on 2025-12-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_alter_constant_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(limit_choices_to={'key': 'ACTION_TYPES'}, on_delete=django.db.models.deletion.CASCADE, related_name='permission_actions', to='core.constant')),
                ('submenu', models.ForeignKey(limit_choices_to={'key': 'SUBMENUS'}, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.constant')),
            ],
        ),
    ]
