# Generated by Django 5.1.13 on 2025-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_submenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.submenupermission'),
        ),
    ]
