# Generated by Django 5.1.13 on 2025-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_constant_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='roles2',
            field=models.ManyToManyField(blank=True, help_text='Хэрэглэгчид ногдох нэмэлт эрхүүд.', null=True, related_name='roles', to='core.constant', verbose_name='Нэмэлт эрхүүд'),
        ),
    ]
