# Generated by Django 5.1.13 on 2025-12-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_remoteuser_roles2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteuser',
            name='roles',
        ),
    ]
