# Generated by Django 5.1.13 on 2025-12-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_remove_remoteuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteuser',
            old_name='roles2',
            new_name='roles',
        ),
    ]
