# Generated by Django 5.1.13 on 2025-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_rename_roles2_remoteuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='roles',
            field=models.ManyToManyField(help_text='Хэрэглэгчид ногдох нэмэлт эрхүүд.', related_name='roles', to='core.constant', verbose_name='Нэмэлт эрхүүд'),
        ),
    ]
