# Generated by Django 5.1.13 on 2025-12-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_alter_remoteuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
