# Generated by Django 5.2.9 on 2025-12-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0217_remove_remoteuser_role_delete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="soil",
            field=models.ForeignKey(
                blank=True,
                help_text="Хөрсний төрөл.",
                limit_choices_to={"key": "SOILTYPES"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soiltypes",
                to="core.constant",
                verbose_name="Хөрсний шинж",
            ),
        ),
    ]
