# Generated by Django 5.2.9 on 2025-12-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0218_point_soil"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acts",
                to="core.point",
            ),
        ),
    ]
