# Generated by Django 5.2.9 on 2025-12-24 04:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0219_act_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="un",
                        max_length=2000,
                        null=True,
                        verbose_name="Нэр",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "dugaar",
                    models.CharField(
                        blank=True,
                        default="un",
                        max_length=2000,
                        null=True,
                        verbose_name="Дугаар",
                    ),
                ),
                (
                    "signed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Эхэлсэн огноо"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дуусах огноо"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rojects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хэрэглэгч",
                    ),
                ),
            ],
        ),
    ]
