# Generated by Django 5.2.9 on 2025-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0220_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="geom",
        ),
        migrations.AddField(
            model_name="project",
            name="percent",
            field=models.CharField(
                blank=True, default="un", max_length=2000, null=True, verbose_name="Нэр"
            ),
        ),
    ]
