# Generated by Django 5.2.9 on 2025-12-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0221_remove_project_geom_project_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="oldid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
