# Generated by Django 5.2.9 on 2025-12-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0222_project_oldid"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
                verbose_name="Төсөл",
            ),
        ),
    ]
