# Generated by Django 5.2.9 on 2025-12-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0223_measurement_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="recount",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
                verbose_name="Төсөл",
            ),
        ),
    ]
