# Generated by Django 5.2.9 on 2025-12-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0224_recount_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="horht",
            new_name="horht",
        ),
    ]
