# Generated by Django 5.2.9 on 2025-12-31 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0226_rename_horht_measurement_horht"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="hOrht",
            new_name="horht",
        ),
    ]
