# Generated by Django 5.2.9 on 2026-02-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0227_rename_horht_measurement_horht"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recount",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зөвшөөрсөн",
            ),
        ),
        migrations.AlterField(
            model_name="recount",
            name="counted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зөвшөөрсөн",
            ),
        ),
    ]
