# Generated by Django 5.2.9 on 2026-03-04 05:21

from django.db import migrations, models


def migrate_fk_to_m2m(apps, schema_editor):
    """Хуучин unit FK утгыг шинэ unit M2M руу хуулах."""
    RemoteUser = apps.get_model('core', 'RemoteUser')
    db_alias = schema_editor.connection.alias
    for user in RemoteUser.objects.using(db_alias).filter(unit_old_id__isnull=False):
        user.unit.add(user.unit_old_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0228_alter_recount_confirmed_by_alter_recount_counted_by"),
    ]

    operations = [
        # 1. FK талбарыг түр нэрлэх
        migrations.RenameField(
            model_name="remoteuser",
            old_name="unit",
            new_name="unit_old",
        ),
        # 2. M2M талбар нэмэх
        migrations.AddField(
            model_name="remoteuser",
            name="unit",
            field=models.ManyToManyField(
                blank=True,
                help_text="Харьяалагдах захиргааны нэгжүүд.",
                related_name="relatedunits",
                to="core.adminunit",
                verbose_name="Хил",
            ),
        ),
        # 3. Өгөгдөл шилжүүлэх
        migrations.RunPython(migrate_fk_to_m2m, migrations.RunPython.noop),
        # 4. Хуучин FK талбарыг устгах
        migrations.RemoveField(
            model_name="remoteuser",
            name="unit_old",
        ),
    ]
