# Generated by Django 6.0.5 on 2026-06-05 07:52

import django.db.models.deletion
import portal.utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_remoteuser_unit_fk_to_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('name', models.CharField(blank=True, default='un', max_length=2000, null=True, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Гарсан огноо')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дугаар')),
                ('document', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Баримт бичиг')),
                ('signer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарын үсэг')),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'key': 'ORDER_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalorders', to='core.constant', verbose_name='Төрөл')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalorders', to='core.adminunit', verbose_name='ЗЗНэгж')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
