# Generated by Django 6.0.5 on 2026-06-05 08:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import portal.utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_legalorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('name', models.CharField(blank=True, help_text='Албан ёсны нэр.', max_length=1000, null=True, verbose_name='Нэр')),
                ('number', models.CharField(blank=True, help_text='Системийн дугаар.', max_length=1000, null=True, verbose_name='Дугаар')),
                ('geoloc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Газарзүйн байрлал')),
                ('is_approved', models.BooleanField(blank=True, default=False, help_text='Төлөв', null=True, verbose_name='Төлөв')),
                ('nomek', models.ManyToManyField(blank=True, related_name='nomeknames', to='core.nomek', verbose_name='Нэрлэвэр')),
                ('status', models.ForeignKey(limit_choices_to={'key': 'GEONAME_STATUS'}, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.constant', verbose_name='Төрөл')),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerlocations', to='core.constant', verbose_name='Төрөл')),
                ('unit', models.ManyToManyField(blank=True, related_name='unitnames', to='core.adminunit', verbose_name='Хил')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path)),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Зөвшөөрсөн')),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('qr_data', models.CharField(blank=True, max_length=5000, verbose_name='QR data')),
                ('qrcode', models.ImageField(blank=True, upload_to=portal.utils.functions.photo_upload_path)),
                ('link', models.URLField(blank=True, max_length=3000, null=True)),
                ('desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actengineers', to=settings.AUTH_USER_MODEL, verbose_name='Хувийн хэрэг хөтөлсөн')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='core.geoname')),
                ('officer', models.ForeignKey(blank=True, limit_choices_to={'is_citizen': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to=settings.AUTH_USER_MODEL, verbose_name='Хүлээн авсан')),
            ],
        ),
        migrations.RemoveField(
            model_name='act',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='act',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='act',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='act',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='act',
            name='point',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='journal_engineer',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='network',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='org',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='passport_engineer',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='point',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='step',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='system',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='point',
            name='center',
        ),
        migrations.RemoveField(
            model_name='point',
            name='nomek',
        ),
        migrations.RemoveField(
            model_name='point',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='point',
            name='status',
        ),
        migrations.RemoveField(
            model_name='point',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recount',
            name='point',
        ),
        migrations.RemoveField(
            model_name='recount',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='recount',
            name='counted_by',
        ),
        migrations.RemoveField(
            model_name='recount',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='recount',
        ),
        migrations.DeleteModel(
            name='OldPoint',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['name__name'], 'verbose_name_plural': 'Цэгийн зураг'},
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurementphotos', to='core.geoname', verbose_name='Цэг'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.geoname'),
        ),
        migrations.AlterField(
            model_name='report',
            name='measurements',
            field=models.ManyToManyField(related_name='reports', to='core.geoname'),
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='ReCount',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
