# Generated by Django 6.0.5 on 2026-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_geoname_passport_remove_act_engineer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminunit',
            name='centername',
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='center',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
