# Generated by Django 6.0.5 on 2026-06-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_remove_adminunit_centername_alter_adminunit_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminCenter',
        ),
    ]
