# Generated by Django 6.0.5 on 2026-06-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_delete_admincenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminunit',
            name='center',
        ),
    ]
