# Generated by Django 6.0.5 on 2026-06-05 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_remove_adminunit_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр')),
                ('source', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Эх сурвалж')),
                ('utga', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Утга')),
                ('lang', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Хэл')),
                ('child', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Хамааралтай нэр')),
            ],
        ),
        migrations.AlterField(
            model_name='geoname',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дугаар'),
        ),
        migrations.CreateModel(
            name='NameContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр')),
                ('register', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Регистр')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Хаяг')),
                ('phone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Утас')),
                ('email', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Имэйл')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namecontacts', to='core.nameoption', verbose_name='Нэр')),
            ],
        ),
        migrations.CreateModel(
            name='RequestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Өргөрөг')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Уртраг')),
                ('age', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_AGES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestages', to='core.constant', verbose_name='Нас')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestnames', to='core.geoname', verbose_name='Нэр')),
                ('option', models.ManyToManyField(blank=True, related_name='requestoptions', to='core.nameoption', verbose_name='Нэрлэвэр')),
                ('purpose', models.ManyToManyField(blank=True, limit_choices_to={'key': 'REQUEST_PURPOSES'}, related_name='requestpurposes', to='core.constant', verbose_name='Төрөл')),
                ('status', models.ForeignKey(limit_choices_to={'key': 'REQUEST_STATUS'}, on_delete=django.db.models.deletion.CASCADE, related_name='requeststatuses', to='core.constant', verbose_name='Төрөл')),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nametypes', to='core.constant', verbose_name='Төрөл')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
