# Generated by Django 6.0.5 on 2026-06-05 11:39

import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_nameoption_alter_geoname_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Хувийн хэрэг'),
        ),
    ]
