# Generated by Django 6.0.5 on 2026-06-05 11:45

import django.db.models.deletion
import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0236_geoname_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Photo'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='type',
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Зураг'),
        ),
        migrations.AddField(
            model_name='photo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Хавсаргах файл')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Attach',
            },
        ),
    ]
