# Generated by Django 6.0.5 on 2026-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_alter_photo_options_remove_photo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='ordernames', to='core.legalorder', verbose_name='Эрх зүйн баримт бичиг'),
        ),
    ]
