# Generated by Django 6.0.5 on 2026-06-05 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_geoname_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoname',
            name='geoloc',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Газарзүйн байрлал'),
        ),
    ]
