# Generated by Django 6.0.5 on 2026-06-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_alter_geoname_geoloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='status',
        ),
        migrations.AlterField(
            model_name='constant',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='color',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Өнгө'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Түлхүүр'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Харуулах нэр'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.constant', verbose_name='Харъяалагдах тогтмол'),
        ),
    ]
