# Generated by Django 6.0.5 on 2026-06-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_remove_geoname_status_alter_constant_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameoption',
            old_name='source',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='nameoption',
            name='child',
        ),
        migrations.RemoveField(
            model_name='nameoption',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='nameoption',
            name='utga',
        ),
    ]
