# Generated by Django 6.0.5 on 2026-06-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_rename_source_nameoption_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='is_border',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Хил цэс эсэх'),
        ),
    ]
