# Generated by Django 6.0.5 on 2026-06-07 01:46

import django.db.models.deletion
import portal.utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_geoname_is_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Овог'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=portal.utils.functions.photo_upload_path, verbose_name='Зураг'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestedcontacts', to=settings.AUTH_USER_MODEL, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='nameoption',
            name='name2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр 2'),
        ),
    ]
