# Generated by Django 6.0.5 on 2026-06-07 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_namecontact_first_name_namecontact_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecontact',
            name='name',
        ),
        migrations.AddField(
            model_name='namecontact',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namecontacts', to='core.requestname', verbose_name='Нэр'),
        ),
    ]
