# Generated by Django 6.0.5 on 2026-06-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_remove_namecontact_name_namecontact_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='org',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'LEGAL_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalorgs', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
