# Generated by Django 6.0.5 on 2026-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_legalorder_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='types',
            field=models.ManyToManyField(limit_choices_to={'key': 'GEONAME_TYPES'}, related_name='types', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
