# Generated by Django 6.0.5 on 2026-06-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_geoname_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='types',
        ),
    ]
