# Generated by Django 6.0.5 on 2026-06-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_remove_geoname_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=300, null=True, verbose_name='Хүлээн авагч имэйл')),
                ('to_user', models.CharField(blank=True, max_length=300, null=True, verbose_name='Хүлээн авагч')),
                ('subject', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Гарчиг')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Агуулга')),
                ('status', models.CharField(choices=[('sent', 'Амжилттай'), ('failed', 'Амжилтгүй')], default='sent', max_length=20, verbose_name='Төлөв')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Алдаа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Огноо')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'key': 'MAIL_CATEGORIES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maillogs', to='core.constant', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name_plural': 'Мэдэгдэл (имэйл)',
                'ordering': ['-created_at'],
            },
        ),
    ]
