# Generated by Django 6.0.5 on 2026-06-10 09:22
#
# point төслөөс хуулагдаж ирсэн AI/chat болон geodetic (Number, Road) моделиудыг
# цэвэрлэнэ. Анхны autogen хувилбар нь operation-ийн дараалал буруугаас болж
# `FieldDoesNotExist: EntityAlias has no field named 'entity'` алдаа өгч байсан
# (AlterUniqueTogether нь холбогдох RemoveField-ийн дараа орсон).
#
# Иймд SeparateDatabaseAndState ашиглав:
#   - state_operations: Django-ийн migration state-ийг зөв болгож моделиудыг арилгана.
#   - database_operations: бодит DB дээр зөвхөн idempotent `DROP TABLE IF EXISTS
#     ... CASCADE` ажиллана — дараалал, FK хамаарал, эсвэл хүснэгт аль хэдийн
#     устсан эсэхээс үл хамааран найдвартай (зарим орфан хүснэгт гар SQL-ээр
#     устсан байж болзошгүй).
from django.db import migrations


# 0249-д устгагдаж буй бүх моделийн хүснэгт (state-аас баталгаажуулсан нэрс)
_DROP_TABLES = [
    'core_chatlog',
    'core_conversation',
    'core_message',
    'core_entityalias',
    'core_gazetteerlink',
    'core_responsetemplate',
    'core_intentslot',
    'core_number',
    'core_regexrule',
    'core_slottype',
    'core_road',
    'core_trainingutterance',
    'core_intent',
    'core_entity',
    'core_entitytype',
]

_DROP_SQL = '\n'.join(f'DROP TABLE IF EXISTS {t} CASCADE;' for t in _DROP_TABLES)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_maillog'),
    ]

    state_operations = [
        migrations.DeleteModel(name='ChatLog'),
        migrations.RemoveField(model_name='message', name='conversation'),
        migrations.AlterUniqueTogether(name='entityalias', unique_together=None),
        migrations.RemoveField(model_name='entityalias', name='entity'),
        migrations.AlterUniqueTogether(name='entity', unique_together=None),
        migrations.RemoveIndex(model_name='entity', name='core_entity_canonic_769b2c_idx'),
        migrations.RemoveField(model_name='gazetteerlink', name='entity_type'),
        migrations.AlterUniqueTogether(name='intentslot', unique_together=None),
        migrations.RemoveField(model_name='intentslot', name='intent'),
        migrations.RemoveField(model_name='intentslot', name='slot'),
        migrations.AlterUniqueTogether(name='responsetemplate', unique_together=None),
        migrations.RemoveField(model_name='responsetemplate', name='intent'),
        migrations.RemoveField(model_name='number', name='network'),
        migrations.RemoveField(model_name='number', name='unit'),
        migrations.RemoveField(model_name='number', name='user'),
        migrations.RemoveField(model_name='regexrule', name='slot'),
        migrations.RemoveField(model_name='road', name='paver'),
        migrations.RemoveField(model_name='road', name='state'),
        migrations.RemoveIndex(model_name='trainingutterance', name='core_traini_sv_ea42b2_gin'),
        migrations.RemoveField(model_name='trainingutterance', name='intent'),
        migrations.RemoveField(model_name='entity', name='type'),
        migrations.DeleteModel(name='Conversation'),
        migrations.DeleteModel(name='Message'),
        migrations.DeleteModel(name='EntityAlias'),
        migrations.DeleteModel(name='GazetteerLink'),
        migrations.DeleteModel(name='ResponseTemplate'),
        migrations.DeleteModel(name='IntentSlot'),
        migrations.DeleteModel(name='Number'),
        migrations.DeleteModel(name='RegexRule'),
        migrations.DeleteModel(name='SlotType'),
        migrations.DeleteModel(name='Road'),
        migrations.DeleteModel(name='Entity'),
        migrations.DeleteModel(name='EntityType'),
        migrations.DeleteModel(name='Intent'),
        migrations.DeleteModel(name='TrainingUtterance'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[
                migrations.RunSQL(
                    sql=_DROP_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
