# Generated by Django 6.0.5 on 2026-06-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_drop_orphan_measurement_old'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stylerule',
            name='core_styler_is_visi_a8b522_idx',
        ),
        migrations.AddField(
            model_name='stylerule',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Легендэд харагдах нэр (заавал биш)', max_length=120),
        ),
        migrations.AlterField(
            model_name='layergroupitem',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='core.constant'),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='layer',
            field=models.ForeignKey(limit_choices_to={'key': 'GEONAME_TYPES'}, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.constant'),
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='name',
        ),
    ]
