# Generated by Django 6.0.5 on 2026-06-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_remove_stylerule_core_styler_is_visi_a8b522_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='layer',
            name='core_layer_is_publ_02fdf1_idx',
        ),
        migrations.RemoveField(
            model_name='stylerule',
            name='title',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
