# Generated by Django 6.0.5 on 2026-06-11 07:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import portal.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_remove_layer_core_layer_is_publ_02fdf1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoname',
            name='orders',
        ),
        migrations.AddField(
            model_name='legalorder',
            name='names',
            field=models.ManyToManyField(blank=True, related_name='legalorders', to='core.geoname', verbose_name='Нэрлэвэр'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='document',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'DOCUMENT_TYPES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namecontacts', to='core.legalorder', verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namecontacts', to='core.project', verbose_name='Төсөл'),
        ),
        migrations.AddField(
            model_name='namecontact',
            name='role',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'RECOUNT_ROLES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namecontacts', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='ReCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Төсөл')),
                ('loc', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Газарзүйн байрлал')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recounts', to='core.geoname', verbose_name='Нэр')),
                ('nomeks', models.ManyToManyField(blank=True, related_name='recount100', to='core.nomek', verbose_name='Нэрлэвэр')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recounts', to='core.project', verbose_name='Төсөл')),
                ('status', models.ForeignKey(limit_choices_to={'key': 'RECOUNT_STATUS'}, on_delete=django.db.models.deletion.CASCADE, related_name='recountstatuses', to='core.constant', verbose_name='Төрөл')),
                ('step', models.ForeignKey(blank=True, limit_choices_to={'key': 'RECOUNT_STEPS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recountsteps', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
        migrations.CreateModel(
            name='ReCountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Зураг')),
                ('names', models.ManyToManyField(related_name='recountmaps', to='core.recount', verbose_name='Нэрс')),
                ('sources', models.ManyToManyField(blank=True, limit_choices_to={'key': 'SOURCES'}, related_name='recountmapssources', to='core.constant', verbose_name='Төрөл')),
            ],
        ),
    ]
