# Generated by Django 6.0.5 on 2026-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_remove_geoname_orders_legalorder_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projectorders', to='core.project', verbose_name='Төслүүд'),
        ),
    ]
