# Generated by Django 6.0.5 on 2026-06-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_legalorder_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recount',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'RECOUNT_STATUS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recountstatuses', to='core.constant', verbose_name='Төрөл'),
        ),
    ]
