# Generated by Django 6.0.5 on 2026-06-11 11:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import portal.utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_alter_recount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomek',
            name='is_mapped',
        ),
        migrations.RemoveField(
            model_name='project',
            name='oldid',
        ),
        migrations.AlterField(
            model_name='nomek',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Төв цэг'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Хил'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='nomek',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.nomek', verbose_name='Дээд нэрлэвэр'),
        ),
        migrations.AlterField(
            model_name='nomek',
            name='scale',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MAPSCALES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='core.constant', verbose_name='Төрөл'),
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Нэр')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Байгуулсан огноо')),
                ('dissolved_date', models.DateField(blank=True, null=True, verbose_name='Татан буугдсан огноо')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dissolved_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dissolved_councils', to='core.legalorder', verbose_name='Татан буулгасан баримт')),
                ('established_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='established_councils', to='core.legalorder', verbose_name='Байгуулсан баримт')),
                ('kind', models.ForeignKey(blank=True, limit_choices_to={'key': 'COUNCIL_KINDS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_kinds', to='core.constant', verbose_name='Төрөл')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'key': 'COUNCIL_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_statuses', to='core.constant', verbose_name='Төлөв')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='councils', to='core.adminunit', verbose_name='Харьяа нэгж')),
            ],
        ),
        migrations.CreateModel(
            name='RasterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('map_date', models.DateField(blank=True, null=True, verbose_name='Гарсан огноо')),
                ('is_geo', models.BooleanField(default=False, verbose_name='Холболттой эсэх')),
                ('file', models.FileField(blank=True, null=True, upload_to=portal.utils.functions.file_upload_path, verbose_name='Газрын зураг')),
                ('names', models.ManyToManyField(blank=True, related_name='namemaps', to='core.geoname', verbose_name='Нэрлэвэр')),
                ('nomek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapnomeks', to='core.nomek', verbose_name='Нэрлэвэр')),
                ('projects', models.ManyToManyField(blank=True, related_name='projectmaps', to='core.project', verbose_name='Төслүүд')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapunits', to='core.adminunit', verbose_name='ЗЗНэгж')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Овог нэр')),
                ('register', models.CharField(blank=True, max_length=20, null=True, verbose_name='Регистр')),
                ('org_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Төлөөлж буй албан тушаал')),
                ('start_date', models.DateField(verbose_name='Томилогдсон огноо')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Чөлөөлөгдсөн огноо')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('appoint_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council_appointments', to='core.legalorder', verbose_name='Томилсон баримт')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.council', verbose_name='Зөвлөл')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Системийн хэрэглэгч')),
                ('position', models.ForeignKey(blank=True, limit_choices_to={'key': 'COUNCIL_POSITIONS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_positions', to='core.constant', verbose_name='Албан тушаал')),
                ('release_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_releases', to='core.legalorder', verbose_name='Чөлөөлсөн баримт')),
            ],
            options={
                'ordering': ['-start_date', 'id'],
                'indexes': [models.Index(fields=['council', 'end_date'], name='core_counci_council_d3c878_idx')],
            },
        ),
    ]
