# Generated by Django 6.0.5 on 2026-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_remove_nomek_is_mapped_remove_project_oldid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='name_eng',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Нэр (English)'),
        ),
    ]
