# Generated by Django 6.0.5 on 2026-06-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_geoname_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Өндөр'),
        ),
        migrations.AddField(
            model_name='geoname',
            name='other',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Бусад'),
        ),
        migrations.CreateModel(
            name='GeoNameSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Боть')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='Хуудас')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Мөр')),
                ('raw_text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Эх мөр')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Итгэлийн оноо')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Хянах шаардлагатай')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.geoname', verbose_name='Нэр')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_sources', to='core.legalorder', verbose_name='Тогтоол')),
            ],
            options={
                'indexes': [models.Index(fields=['volume', 'page'], name='core_geonam_volume_6fcc88_idx')],
            },
        ),
    ]
