# Generated by Django 6.0.5 on 2026-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_constant_is_map_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_cart_id_c09971_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_point_i_03d45a_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentbank',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='report',
            name='measurements',
        ),
        migrations.AddField(
            model_name='recount',
            name='statuses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'key': 'RECOUNT_STATUS'}, related_name='recount_multi_statuses', to='core.constant', verbose_name='Төлөв (олон)'),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='point',
        ),
        migrations.DeleteModel(
            name='QpayToken',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentBank',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
