# Generated by Django 6.0.5 on 2026-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_remove_cart_status_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recount',
            name='status',
        ),
        migrations.AlterField(
            model_name='recount',
            name='statuses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'key': 'RECOUNT_STATUS'}, related_name='recount_multi_statuses', to='core.constant', verbose_name='Төлөв'),
        ),
    ]
