# Generated by Django 6.0.5 on 2026-07-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_remove_recount_status_alter_recount_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemaplayer',
            name='source_type',
            field=models.CharField(choices=[('blank', 'Хоосон (blank)'), ('xyz', 'XYZ (гадаад тайл)'), ('osm', 'OpenStreetMap'), ('wms', 'WMS (GeoServer/GWC)'), ('wmts', 'WMTS (GeoServer/GWC кэш)')], default='wms', max_length=16, verbose_name='Эх сурвалж'),
        ),
    ]
