# Generated by Django 6.0.5 on 2026-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_alter_basemaplayer_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зовхис'),
        ),
    ]
