# Generated by Django 6.0.5 on 2026-07-29 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0265_photo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNameInquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Лавлагааны дугаар')),
                ('purpose', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Зориулалт')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Хүчинтэй хугацаа')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquires', to='core.geoname', verbose_name='Газар зүйн нэр')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'verbose_name_plural': 'GeoNameInquire',
            },
        ),
    ]
