# Generated by Django 6.0.5 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_geonameinquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='projectunits', to='core.adminunit', verbose_name='Хил'),
        ),
    ]
