# Generated by Django 6.0.5 on 2026-07-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_project_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmember',
            name='position',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'MEMBER_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_positions', to='core.constant', verbose_name='Албан тушаал'),
        ),
    ]
