# Generated by Django 6.0.5 on 2026-07-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_projectarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='recount',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'GEONAME_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recounttypes', to='core.constant', verbose_name='Ангилал'),
        ),
    ]
