# Generated by Django 6.0.5 on 2026-07-31 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_recount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн')),
                ('last_view', models.DateTimeField(auto_now_add=True, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн')),
                ('views', models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Овог нэр')),
                ('register', models.CharField(blank=True, max_length=20, null=True, verbose_name='Регистр')),
                ('org_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Төлөөлж буй албан тушаал')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_documents', to='core.legalorder', verbose_name='Томилсон баримт')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Системийн хэрэглэгч')),
                ('position', models.ForeignKey(blank=True, limit_choices_to={'key': 'PROJECT_MEMBER_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_positions', to='core.constant', verbose_name='Албан тушаал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project', verbose_name='Төсөл')),
                ('user', models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
            ],
            options={
                'ordering': ['-created_date', 'id'],
                'indexes': [models.Index(fields=['project', 'created_date'], name='core_projec_project_3e4e63_idx')],
            },
        ),
    ]
