# Generated by Django 6.0.5 on 2026-07-31 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Утас'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='step',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'RECOUNT_STEPS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_member_steps', to='core.constant', verbose_name='Үе шат'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='core.adminunit', verbose_name='Сум/Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_documents', to='core.legalorder', verbose_name='Томилсон баримт'),
        ),
    ]
