# Generated by Django 6.0.5 on 2026-07-31 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_projectmember_phone_projectmember_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmap',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printmaps', to='core.project', verbose_name='Төсөл'),
        ),
    ]
