# Generated by Django 6.0.5 on 2026-07-31 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_printmap_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='recount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Энэхүү бичлэг үүссэн огноо, цаг.', verbose_name='Бүртгэсэн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recount',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Хэрэглэгч хамгийн сүүлд үзсэн огноо, цаг.', verbose_name='Сүүлд үзсэн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recount',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Сүүлд шинэтгэл хийгдсэн огноо, цаг.', verbose_name='Шинэчилсэн'),
        ),
        migrations.AddField(
            model_name='recount',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Энэхүү бичлэгийг үүсгэсэн хэрэглэгч.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн'),
        ),
        migrations.AddField(
            model_name='recount',
            name='views',
            field=models.IntegerField(default=1, help_text='Энэ бичлэг рүү хандсан нийт тоо.', verbose_name='Хандалт'),
        ),
    ]
