# Generated by Django 6.0.5 on 2026-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_basemap_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recount',
            name='is_border',
            field=models.BooleanField(default=False, verbose_name='Хилийн цэс'),
        ),
    ]
