# Generated by Django 6.0.5 on 2026-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0277_recount_is_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoname',
            name='borderunit',
            field=models.ManyToManyField(blank=True, related_name='borderunitnames', to='core.adminunit', verbose_name='Хил'),
        ),
        migrations.AddField(
            model_name='recount',
            name='borderunit',
            field=models.ManyToManyField(blank=True, related_name='borderunitrecounts', to='core.adminunit', verbose_name='Хилийн нэгжүүд'),
        ),
    ]
