# Generated by Django 6.0.5 on 2026-08-24 04:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_legalorder_govlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestname',
            name='geoloc',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Газарзүйн байрлал'),
        ),
    ]
