# Generated by Django 6.0.5 on 2026-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0280_requestname_geoloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaplayer',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Анхдагч (map ачаалахад)'),
        ),
    ]
