# Generated by Django 6.0.5 on 2026-08-24 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0282_relief'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Өндөр')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=32648, verbose_name='Геометр')),
            ],
            options={
                'verbose_name': 'DEM цэг (түр)',
                'verbose_name_plural': 'DEM цэг (түр)',
                'db_table': 'dem_point',
            },
        ),
    ]
