# Generated by Django 6.0.5 on 2026-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_dempoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='relief',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Өндөр баталгаажсан'),
        ),
    ]
