# Generated by Django 6.0.5 on 2026-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0284_relief_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='relief',
            name='height_est',
            field=models.FloatField(blank=True, null=True, verbose_name='Сэргээсэн өндөр'),
        ),
        migrations.AddField(
            model_name='relief',
            name='height_src',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Сэргээсэн эх'),
        ),
        migrations.AddField(
            model_name='relief',
            name='turl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хаяалбарын төрөл'),
        ),
    ]
