# Generated by Django 6.0.5 on 2026-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarea',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='adminarea',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='adminboundary',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='adminboundary',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='contourline',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='contourline',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='geodeticpoint',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='geodeticpoint',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='hydropoint',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='hydropoint',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='landcoverarea',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='landcoverarea',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='railway',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='railway',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='relieffeature',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='relieffeature',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='road',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='road',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='settlementarea',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='settlementarea',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='spotheight',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='spotheight',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='toponym',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='toponym',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='transportstructure',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='transportstructure',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='utilityline',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='utilityline',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='utilitypoint',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='utilitypoint',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='vegetationfeature',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='vegetationfeature',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AddField(
            model_name='watercourse',
            name='name_galig',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)'),
        ),
        migrations.AddField(
            model_name='watercourse',
            name='name_mong',
            field=models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)'),
        ),
        migrations.AlterField(
            model_name='adminarea',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='adminboundary',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='contourline',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='geodeticpoint',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='hydropoint',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='landcoverarea',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='railway',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='relieffeature',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='settlementarea',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='spotheight',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='toponym',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='transportstructure',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='utilityline',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='utilitypoint',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='vegetationfeature',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='waterbody',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
        migrations.AlterField(
            model_name='watercourse',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)'),
        ),
    ]
