# Generated by Django 6.0.5 on 2026-07-25 05:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_adminarea_name_galig_adminarea_name_mong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='addr_housenumber',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Байрны дугаар'),
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)')),
                ('name_mong', models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)')),
                ('name_galig', models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)')),
                ('name_en', models.CharField(blank=True, max_length=254, verbose_name='Нэр (англи)')),
                ('source_osm_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='OSM id')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Тэмдэглэл')),
                ('inspire_namespace', models.CharField(default='MN.GEO', max_length=64, verbose_name='INSPIRE namespace')),
                ('inspire_local_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='INSPIRE localId')),
                ('inspire_version', models.CharField(blank=True, max_length=32, verbose_name='Хувилбар (versionId)')),
                ('begin_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар эхэлсэн')),
                ('end_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар дууссан')),
                ('ext', models.JSONField(blank=True, default=dict, verbose_name='Нэмэлт атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Байрлал')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'BUSINESS_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Төрөл')),
                ('source', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'SOURCE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Эх сурвалж')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'LIFECYCLE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Төлөв')),
            ],
            options={
                'verbose_name': 'Худалдаа, үйлчилгээ',
                'verbose_name_plural': '84 · Худалдаа, үйлчилгээ',
                'db_table': 'map_business_service',
            },
        ),
        migrations.CreateModel(
            name='GovernmentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)')),
                ('name_mong', models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)')),
                ('name_galig', models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)')),
                ('name_en', models.CharField(blank=True, max_length=254, verbose_name='Нэр (англи)')),
                ('source_osm_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='OSM id')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Тэмдэглэл')),
                ('inspire_namespace', models.CharField(default='MN.GEO', max_length=64, verbose_name='INSPIRE namespace')),
                ('inspire_local_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='INSPIRE localId')),
                ('inspire_version', models.CharField(blank=True, max_length=32, verbose_name='Хувилбар (versionId)')),
                ('begin_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар эхэлсэн')),
                ('end_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар дууссан')),
                ('ext', models.JSONField(blank=True, default=dict, verbose_name='Нэмэлт атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Байрлал')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Үйлчилгээний төрөл')),
                ('source', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'SOURCE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Эх сурвалж')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'LIFECYCLE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Төлөв')),
            ],
            options={
                'verbose_name': 'Төрийн үйлчилгээ',
                'verbose_name_plural': '83 · Төрийн үйлчилгээ',
                'db_table': 'map_governmental_service',
            },
        ),
        migrations.CreateModel(
            name='OtherConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Нэр (кирилл)')),
                ('name_mong', models.CharField(blank=True, max_length=254, verbose_name='Нэр (монгол бичиг)')),
                ('name_galig', models.CharField(blank=True, max_length=254, verbose_name='Нэр (галиг)')),
                ('name_en', models.CharField(blank=True, max_length=254, verbose_name='Нэр (англи)')),
                ('source_osm_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='OSM id')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Тэмдэглэл')),
                ('inspire_namespace', models.CharField(default='MN.GEO', max_length=64, verbose_name='INSPIRE namespace')),
                ('inspire_local_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='INSPIRE localId')),
                ('inspire_version', models.CharField(blank=True, max_length=32, verbose_name='Хувилбар (versionId)')),
                ('begin_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар эхэлсэн')),
                ('end_lifespan', models.DateTimeField(blank=True, null=True, verbose_name='Хувилбар дууссан')),
                ('ext', models.JSONField(blank=True, default=dict, verbose_name='Нэмэлт атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Геометр')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'OTHER_CONSTRUCTION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Төрөл')),
                ('source', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'SOURCE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Эх сурвалж')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'key': 'LIFECYCLE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='map.mapconstant', verbose_name='Төлөв')),
            ],
            options={
                'verbose_name': 'Бусад байгууламж',
                'verbose_name_plural': '63 · Бусад байгууламж',
                'db_table': 'map_other_construction',
            },
        ),
    ]
